### ISSUE TITLE
[Clientcrash] java.lang.Float cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by Thyriel** [capnkirok/animania#19] opened 2017-02-22 14:08 UTC
Animania-1.10.2-0.9.8 BETA
Clientlog: http://pastebin.com/udpf6jyF

Happens occasionally when running around. Sounds like a pig in mud is generating a problem. When this happens client crashes imediately again after reconnecting to the server. (Need to delete playerdata file to solve it so he doesn't spawn at the location causing the crash)

**Comment by capnkirok** [comment] 2017-02-22 15:36
Ooh, that's a bad one. Thanks for the log file.

**Comment by capnkirok** [comment] 2017-02-23 17:14
Hey, I'm not able to replicate. This is very strange, as this by default a Boolean value, it's never an Integer, so it would never cast it as such. I'm going to try to put in error trapping, which really shouldn't be necessary... but we'll see what happens.

**Comment by Thyriel** [comment] 2017-02-24 12:54
I played around a bit trying to pin the error down and seems it's not on your end.
When i came to the point that it didn't crashed in singleplayer but crashed while playing on my server with only animania installed as soon as i spawned a yorkshire pig, i thought i give it a try looking at the forge versions.
My server had forge 2202, my client 2185 (recommended). Updated the server to the newest (2239) forge and it doesn't crash now.
So i guess the problem lies somewhere in the forge versions between current "recommended" and "newest"

**Comment by capnkirok** [comment] 2017-02-24 14:12
Oh, that is good news! Thank you for following up :)

**Comment by Thyriel** [comment] 2017-02-24 15:54
Not really ;) Seems you missed my edit's in your email notification. It's better with newest forge version, but still not working without crashing sometimes. But should be easy now for you to reproduce. Just install animania on a server, connect to it and spawn some yorkshire sow's

**Comment by capnkirok** [comment] 2017-02-25 08:20
Ha ha ha. Well, if it's consistently reproducible that's good. I wonder why it's only the Yorkshire Sow...

**Comment by Thyriel** [comment] 2017-02-25 08:41
Good question ;) It's a long time since i last programed but i would try making a file comparison between the yorkshire and others to see if there's anywhere a difference.
Or just add options on the config file to disable individual animals, i think that would at least help me bypass the error.

**Comment by capnkirok** [comment] 2017-02-25 22:00
By the way I did do this, but with version forge-1.10.2-12.18.1.2043. No crashes. Will update and see what happens.

**Comment by capnkirok** [comment] 2017-02-25 22:21
Still not able to reproduce. But... I think I have a fix for this. I know where the error is, so I've rewritten the code to use a completely different variable. Will come in the 1.0 release.

**Comment by Thyriel** [comment] 2017-02-26 14:35
Hmm 2043 is a really old forge version for 1.10. Maybe the problem is that forge changed something somewhere in the ~100 versions since then.

**Comment by capnkirok** [comment] 2017-02-26 15:25
Let me know later tonight or tomorrow if the fixed worked. Should have 1.0 up in about 1.5 hours

**Comment by Thyriel** [comment] 2017-02-26 20:59
Works like a charm now and server RAM usage improved greatly too :) Much thanks

**Closed** 2017-02-27 06:46 UTC
Labels: bug, fixed in dev
