### ISSUE TITLE
Wrong Animals Spawning in BOP Biomes

### ISSUE THREAD

**Issue by Gift-of-Names** [capnkirok/animania#394] opened 2017-10-17 01:16 UTC
After updating Animania to version 1.3.5 in Forge 1.12.2, I noticed that only default Animania animals were spawning in BOP biomes. (This was somewhat disappointing as I remembered an area that had longhorns).

**Comment by capnkirok** [comment] 2017-10-21 20:00
All of the spawning is based on biome dictionary. It should be working properly. Sometimes the default do spawn in BOP biomes. Are you still seeing the issue (because I don't in my testing).

**Comment by capnkirok** [comment] 2017-10-21 21:34
Ok, I just tried this in the version you specified, and had similar results. I find it hard to believe that BOP is not using Biome Dictionary. I also noticed it handles it's own spawning... including vanilla animals (like rabbits) when Animania should be replacing them. I think this needs to be cross posted to Glitchfiend.

**Comment by Gift-of-Names** [comment] 2017-10-22 16:00
I am still having this issue, but I see my reply is a little late and maybe unnecessary. Another example would be finding nothing but Friesians in the highlands (fortunately I found an Extreme Hills!).

**Comment by capnkirok** [comment] 2017-10-26 21:38
Ok, I just figured out what the problem is and it's on my end. Some spawns are working properly, the ones that happen naturally. However, the 'replacement' spawns (where I replace the vanilla animals) are not, because they do not check BiomeDictionary. This explains why it sometimes works and sometimes not. 

This will be fixed. Thanks for reporting this, I am a big fan of BOP.

**Closed** 2017-10-29 16:42 UTC
Labels: 1.10.2, 1.11.2, 1.12, bug, compat, fixed in next release
