### ISSUE TITLE
Harvestcraft Animania conflict

### ISSUE THREAD

**Issue by annasoaps** [capnkirok/animania#570] opened 2018-02-17 19:20 UTC
### Expected Behavior
In harvestcraft fruit trees spawn naturally. They are sparse but they spawn in the wild

### Actual Behavior
When I run harvestcraft together with animania I can't find any fruit trees at all. I can craft an apple tree if I have three apples and a sapling, but since I can't find any other fruits it's impossible to craft more trees.

### Steps to Reproduce
Run the two mods together (I don't use any other mods)

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 minecraft, 
animania-1.12.2-1.4.5
Pam's+HarvestCraft+1.12.2p
But I have had this problem since 1.11

**Comment by Deshiba** [comment] 2018-02-18 01:37
Can't reproduce this with a fresh install and a new world:
![2018-02-18_02 34 18](https://user-images.githubusercontent.com/10565800/36347303-6584f6fe-1454-11e8-9d7d-901a5c23113d.png)

For complete info, could you answer the following questions.
* What is your version of craft studio?
* Is this a new world or did you upgrade from 1.11?
** If so, did you explore new chunks? 
* could you include your configuration files for both animania and harvest craft?

**Comment by capnkirok** [comment] 2018-02-18 12:06
Animania doesn't touch WorldGen, so I would be highly suspect of this.. unless Pam is doing something when Animania is installed. But will test.

**Comment by annasoaps** [comment] 2018-02-18 12:48
Thanks so much for trying to help! Very much appreciated!
I use this version of craft studio: CraftStudio-1.0.0.93-mc1.12-alpha

It worked on all versions of 1.10 of minecraft and earlier, but it is with the later versions I have had problems. I have tried new versions of both mods when they come out, and I always start with a new world, and never any fruit trees.

Here are the config files:
Animania:
# Configuration file

general {

    gamerules {
        # Allow eggs to be thrown
        B:allowEggThrowing=false

        # Allow random mobs to spawn on Animania animals
        B:allowMobRiding=true

        # Allow dispensers to place seeds
        B:allowSeedDispenserPlacement=true

        # Allow the trough to be automated with hoppers/pipes
        B:allowTroughAutomation=true

        # Animals do not have to eat or drink
        B:ambianceMode=false

        # Animals can attack others
        B:animalsCanAttackOthers=true

        # Animals starve to death when not fed and watered
        B:animalsStarve=false

        # Ticks that a Cheese takes to mature
        I:cheeseMaturityTime=24000

        # Disable cart and wagon
        B:disableRollingVehicles=false

        # Disable salt creation using cheese mold
        B:disableSaltCreation=false
        B:enableVanillaMeatRecipes=false

        # Multiplier for reducing fall damage when animals are leashed
        D:fallDamageReduceMultiplier=0.44999998807907104

        # Foods give bonus effects
        B:foodsGiveBonusEffects=true

        # Capacity of RF that the Hamster Wheel has
        I:hamsterWheelCapacity=200000

        # RF/tick that the Hamster wheel generates while in use
        I:hamsterWheelRFGeneration=20

        # Ticks that the hamster stays in the wheel before it needs more food
        I:hamsterWheelUseTime=900

        # Plant blocks removed after animal eats
        B:plantsRemovedAfterEating=true

        # Remove vanilla Chickens
        B:replaceVanillaChickens=true

        # Remove vanilla Cows
        B:replaceVanillaCows=true

        # Remove vanilla Horses
        B:replaceVanillaHorses=false

        # Remove vanilla Pigs
        B:replaceVanillaPigs=true

        # Remove vanilla Rabbits
        B:replaceVanillaRabbits=true

        # Remove vanilla Sheep
        B:replaceVanillaSheep=true

        # Shift-Right-Click for Seed Placement
        B:shiftSeedPlacement=false

        # Show mod update notification at startup
        B:showModUpdateNotification=true

        # Show male parts (modesty flag)
        B:showParts=true

        # Show particles when animals are unhappy
        B:showUnhappyParticles=true

        # Can sleep using Wagon
        B:sleepAllowedWagon=true

        # Food Items that can be placed in the trough (use # for meta)
        S:troughFood <
            minecraft:wheat
            simplecorn:corncob
            harvestcraft:barleyitem
            harvestcraft:oatsitem
            harvestcraft:ryeitem
            harvestcraft:cornitem
            minecraft:apple
            minecraft:carrot
            minecraft:beetroot
            minecraft:potato
            minecraft:poisonous_potato
         >

        # Water blocks removed after large animals drink
        B:waterRemovedAfterDrinking=true
    }

    drops {
        # Set Custom Chicken Drop (if enabled)
        S:chickenDrop=animania:raw_prime_chicken

        # Set Custom Chicken Secondary Drop
        S:chickenDrop2=minecraft:feather

        # Set Custom Chicken Secondary Drop Amount
        I:chickenDrop2Amount=1

        # Allow Animania Chickens to drop Eggs
        B:chickensDropEggs=false

        # Allow Animania Chickens to drop Feathers
        B:chickensDropFeathers=true

        # Set Custom Cow Drop (if enabled)
        S:cowDrop=animania:raw_prime_beef

        # Set Custom Cow Secondary Drop
        S:cowDrop2=minecraft:leather

        # Set Custom Cow Secondary Drop Amount
        I:cowDrop2Amount=1

        # Enable Animal Drops from Config
        B:customMobDrops=true

        # Set Custom Dart Frog Drop
        S:dartFrogDrop=

        # Set Custom Dart Frog Secondary Drop
        S:dartFrogDrop2=

        # Set Custom Dart Frog Secondary Drop Amount
        I:dartFrogDrop2Amount=1

        # Set Custom Ferret Drop (if enabled)
        S:ferretDrop=

        # Set Custom Ferret Secondary Drop
        S:ferretDrop2=

        # Set Custom Ferret Secondary Drop Amount
        I:ferretDrop2Amount=1

        # Set Custom Frog Drop
        S:frogDrop=animania:raw_frog_legs

        # Set Custom Frog Secondary Drop
        S:frogDrop2=

        # Set Custom frog Secondary Drop Amount
        I:frogDrop2Amount=1

        # Set Custom Goat Drop
        S:goatDrop=animania:raw_chevon

        # Set Custom Goat Secondary Drop
        S:goatDrop2=

        # Set Custom Goat Secondary Drop Amount
        I:goatDrop2Amount=1

        # Set Custom Hamster Drop (if enabled)
        S:hamsterDrop=animania:hamster_food

        # Set Custom Hamster Secondary Drop
        S:hamsterDrop2=

        # Set Custom Hamster Secondary Drop Amount
        I:hamsterDrop2Amount=1

        # Set Custom Hedgehog Drop (if enabled)
        S:hedgehogDrop=

        # Set Custom Hedgehog Secondary Drop
        S:hedgehogDrop2=

        # Set Custom Hedgehog Secondary Drop Amount
        I:hedgehogDrop2Amount=1

        # Set Custom Horse Drop (if enabled)
        S:horseDrop=

        # Set Custom Horse Secondary Drop
        S:horseDrop2=minecraft:leather

        # Set Custom Horse Secondary Drop Amount
        I:horseDrop2Amount=1

        # Enable Animals Drop their custom meat types
        B:oldMeatDrops=false

        # Set Custom Blue Peacock Drop (if enabled)
        S:peacockBlueDrop=animania:blue_peacock_feather

        # Set Custom Charcoal Peacock Drop (if enabled)
        S:peacockCharcoalDrop=animania:charcoal_peacock_feather

        # Set Custom Peacock Secondary Drop
        S:peacockDrop2=

        # Set Custom Peacock Secondary Drop Amount
        I:peacockDrop2Amount=1

        # Set Custom Opal Peacock Drop (if enabled)
        S:peacockOpalDrop=animania:opal_peacock_feather

        # Set Custom Peach Peacock Drop (if enabled)
        S:peacockPeachDrop=animania:peach_peacock_feather

        # Set Custom Purple Peacock Drop (if enabled)
        S:peacockPurpleDrop=animania:purple_peacock_feather

        # Set Custom Taupe Peacock Drop (if enabled)
        S:peacockTaupeDrop=animania:taupe_peacock_feather

        # Set Custom White Peacock Drop (if enabled)
        S:peacockWhiteDrop=animania:white_peacock_feather

        # Set Custom Pig Drop (if enabled)
        S:pigDrop=animania:raw_prime_pork

        # Set Custom Pig Secondary Drop
        S:pigDrop2=

        # Set Custom Pig Secondary Drop Amount
        I:pigDrop2Amount=1

        # Set Custom Rabbit Drop
        S:rabbitDrop=animania:raw_prime_rabbit

        # Set Custom Rabbit Secondary Drop
        S:rabbitDrop2=minecraft:rabbit_foot

        # Set Custom Rabbit Secondary Drop Amount
        I:rabbitDrop2Amount=1

        # Set Custom Sheep Drop
        S:sheepDrop=animania:raw_prime_mutton

        # Set Custom Sheep Secondary Drop
        S:sheepDrop2=

        # Set Custom Sheep Secondary Drop Amount
        I:sheepDrop2Amount=1

        # Set Custom Toad Drop
        S:toadDrop=

        # Set Custom Toad Secondary Drop
        S:toadDrop2=

        # Set Custom Toad Secondary Drop Amount
        I:toadDrop2Amount=1
    }

    spawn {
        # Number of potential Chicken families per chunk
        I:numberChickenFamilies=2

        # Number of potential Cow families per chunk
        I:numberCowFamilies=1

        # Number of potential Goat families per chunk
        I:numberGoatFamilies=1

        # Number of potential Horse families per chunk
        I:numberHorseFamilies=1

        # Number of potential Pig families per chunk
        I:numberPigFamilies=1

        # Number of potential Rabbit families per chunk
        I:numberRabbitFamilies=1

        # Number of potential Sheep families per chunk
        I:numberSheepFamilies=2

        # Spawn Animania Amphibians in world
        B:spawnAnimaniaAmphibians=true

        # Spawn Animania Chickens in world
        B:spawnAnimaniaChickens=true

        # Spawn Animania Cows in world
        B:spawnAnimaniaCows=true

        # Spawn Animania Goats in world
        B:spawnAnimaniaGoats=true

        # Spawn Animania Horses in world
        B:spawnAnimaniaHorses=true

        # Spawn Animania Peacocks in world
        B:spawnAnimaniaPeacocks=true

        # Spawn Animania Pigs in world
        B:spawnAnimaniaPigs=true

        # Spawn Animania Rabbits in world
        B:spawnAnimaniaRabbits=true

        # Spawn Animania Rodents in world
        B:spawnAnimaniaRodents=true

        # Spawn Animania Sheep in world
        B:spawnAnimaniaSheep=true

        # Spawn limit for Amphibians in loaded chunks
        I:spawnLimitAmphibians=24

        # Spawn limit for Chickens in loaded chunks
        I:spawnLimitChickens=40

        # Spawn limit for Cows in loaded chunks
        I:spawnLimitCows=40

        # Spawn limit for Ferrets in loaded chunks
        I:spawnLimitFerrets=20

        # Spawn limit for Goats in loaded chunks
        I:spawnLimitGoats=40

        # Spawn limit for Hamsters in loaded chunks
        I:spawnLimitHamsters=24

        # Spawn limit for Hedgehogs in loaded chunks
        I:spawnLimitHedgehogs=20

        # Spawn limit for Horses in loaded chunks
        I:spawnLimitHorses=30

        # Spawn limit for Peacocks in loaded chunks
        I:spawnLimitPeacocks=24

        # Spawn limit for Pigs in loaded chunks
        I:spawnLimitPigs=40

        # Spawn limit for Rabbits in loaded chunks
        I:spawnLimitRabbits=36

        # Spawn limit for Sheep in loaded chunks
        I:spawnLimitSheep=40

        # Spawn probability Amphibians in loaded chunks
        I:spawnProbabilityAmphibians=6

        # Spawn probability Chickens in loaded chunks
        I:spawnProbabilityChickens=8

        # Spawn probability Cows in loaded chunks
        I:spawnProbabilityCows=6

        # Spawn probability Ferrets in loaded chunks
        I:spawnProbabilityFerrets=8

        # Spawn probability Goats in loaded chunks
        I:spawnProbabilityGoats=6

        # Spawn probability Hamsters in loaded chunks
        I:spawnProbabilityHamsters=8

        # Spawn probability Hedgehogs in loaded chunks
        I:spawnProbabilityHedgehogs=8
        I:spawnProbabilityHens=6

        # Spawn probability Horses in loaded chunks
        I:spawnProbabilityHorses=6

        # Spawn probability Peacocks in loaded chunks
        I:spawnProbabilityPeacocks=8

        # Spawn probability Pigs in loaded chunks
        I:spawnProbabilityPigs=8

        # Spawn probability Rabbits in loaded chunks
        I:spawnProbabilityRabbits=4

        # Spawn probability Sheep in loaded chunks
        I:spawnProbabilitySheep=6
        I:spawnProbabilitySows=6
    }

    careandfeeding {
        # Food Items that chickens can eat (use # for meta)
        S:chickenFood <
            minecraft:wheat_seeds
            minecraft:melon_seeds
            minecraft:beetroot_seeds
            minecraft:pumpkin_seeds
            simplecorn:corncob
            biomesoplenty:turnip_seeds
            harvestcraft:cornitem
         >

        # Ticks before next incremental growth
        I:childGrowthTick=200

        # Food Items that cows can eat (use # for meta)
        S:cowFood <
            minecraft:wheat
            simplecorn:corncob
            harvestcraft:barleyitem
            harvestcraft:oatsitem
            harvestcraft:ryeitem
            harvestcraft:cornitem
         >

        # Egg hatch chance (1/x)
        I:eggHatchChance=2

        # Ticks between dropping feathers
        I:featherTimer=12000

        # Ticks between feedings
        I:feedTimer=12000

        # Ticks between birthings
        I:gestationTimer=20000

        # Food Items that goats can eat (use # for meta)
        S:goatFood <
            minecraft:wheat
            minecraft:string
            minecraft:stick
            simplecorn:corncob
            harvestcraft:barleyitem
            harvestcraft:oatsitem
            harvestcraft:ryeitem
            harvestcraft:cornitem
         >

        # Food Items that horses can eat (use # for meta)
        S:horseFood <
            minecraft:wheat
            harvestcraft:barleyitem
            harvestcraft:oatsitem
            harvestcraft:ryeitem
            minecraft:apple
            minecraft:carrot
         >

        # Ticks between laying eggs
        I:laidTimer=2000

        # Mammals mate/breed only after hand-feeding
        B:manualBreeding=false

        # Food Items that pigs can eat (use # for meta)
        S:pigFood <
            minecraft:carrot
            minecraft:beetroot
            minecraft:potato
            minecraft:poisonous_potato
            minecraft:bread
         >

        # Ticks between playing
        I:playTimer=4000

        # Food Items that rabbits can eat (use # for meta)
        S:rabbitFood <
            minecraft:wheat
            minecraft:carrot
            minecraft:beetroot
            minecraft:apple
         >

        # Maximum uses of the salt lick
        I:saltLickMaxUses=200

        # Ticks between using Salt Lick
        I:saltLickTick=8000

        # Food Items that sheep can eat (use # for meta)
        S:sheepFood <
            minecraft:wheat
            harvestcraft:barleyitem
            harvestcraft:oatsitem
            harvestcraft:ryeitem
         >

        # Ticks between animals taking starvation damage
        I:starvationTimer=400

        # Ticks between drinking water
        I:waterTimer=8000

        # Ticks before wool regrowth after shearing
        I:woolRegrowthTimer=8000
    }

    foodvalues {
        # Food Value Overrides
        S:foodValueOverrides <
         >
    }

    entity {
        I:BullAngusID=507
        I:BullFriesianID=504
        I:BullHerefordID=513
        I:BullHolsteinID=501
        I:BullLonghornID=510
        I:CalfAngusID=508
        I:CalfFriesianID=505
        I:CalfHerefordID=514
        I:CalfHolsteinID=502
        I:CalfLonghornID=511
        I:ChickLeghornID=535
        I:ChickOrpingtonID=538
        I:ChickPlymouthRockID=532
        I:ChickRhodeIslandRedID=541
        I:ChickWyandotteID=544
        I:CowAngusID=506
        I:CowFriesianID=503
        I:CowHerefordID=512
        I:CowHolsteinID=500
        I:CowLonghornID=509
        I:FerretMaleGreyID=523
        I:FerretMaleWhiteID=526
        I:FoalDraftHorseID=703
        I:HamsterMaleID=520
        I:HedgehogMaleAlbinoID=550
        I:HedgehogMaleID=529
        I:HenLeghornID=533
        I:HenOrpingtonID=536
        I:HenPlymouthRockID=530
        I:HenRhodeIslandRedID=539
        I:HenWyandotteID=542
        I:HogDurocID=613
        I:HogHampshireID=616
        I:HogLargeBlackID=607
        I:HogLargeWhiteID=610
        I:HogOldSpotID=604
        I:HogYorkshireID=601
        I:MareDraftHorseID=701
        I:PeachickBlueID=582
        I:PeachickWhiteID=585
        I:PeacockBlueID=580
        I:PeacockWhiteID=583
        I:PeafowlBlueID=581
        I:PeafowlWhiteID=584
        I:PigletDurocID=614
        I:PigletHampshireID=617
        I:PigletLargeBlackID=608
        I:PigletLargeWhiteID=611
        I:PigletOldSpotID=605
        I:PigletYorkshireID=602
        I:RoosterLeghornID=534
        I:RoosterOrpingtonID=537
        I:RoosterPlymouthRockID=531
        I:RoosterRhodeIslandRedID=540
        I:RoosterWyandotteID=543
        I:SowDurocID=612
        I:SowHampshireID=615
        I:SowLargeBlackID=606
        I:SowLargeWhiteID=609
        I:SowOldSpotID=603
        I:SowYorkshireID=600
        I:StallionDraftHorseID=702
    }

}


Harvestcraft:
# Configuration file

beehiverarity {
    I:beekeeping=10
}


beekeeping {
    # If true, the last item produced by a queen bee will be another queen bee. [default: true]
    B:apiarylastresultequalsQueen=true

    # The higher the value, the more beehives are generated. [range: 0 ~ 32767, default: 10]
    I:beehiveRarity=5

    # Enable generation of beehives. [default: true]
    B:enableBeehiveGeneration=true

    # Allows grubs and cooked grubs to be used in listAllrawmeat and listAllcookedmeat. [default: true]
    B:enablebeegrubaslistAllmeat=true
    B:enablebeehiveGeneration=true
}


candles {
    D:candlelightLevel=0.9375
    I:candlerecipeAmount=4
}


crops {
    # Default: 0.0, This number is added/subtracted from normal fertile crop growth (3.0) and adjacent fertile crop growth (4.0).
    D:cropGrowthSpeed=0.0
    I:cropfoodRestore=1
    D:cropsaturationRestore=0.6000000238418579
    B:cropsdropSeeds=false
    B:enablecropspecialplanting=true

    # Disable to keep giga pickle crop seeds from appearing in dungeon chests
    B:enablegigapickleCrop=true
    D:mealsaturation=1.2000000476837158
    D:meatymealsaturation=1.600000023841858
    B:rightclickharvestCrop=true
    B:rightclickmatureshowcropHearts=false
    D:snacksaturation=0.6000000238418579
}


dimensions {
    B:enableAroma1997sdimensionalworldfruittreeGen=false
    B:enableAroma1997sdimensionalworldgardenGen=false
    B:enabletwilightforestfruittreeGen=false
    B:enabletwilightforestgardenGen=false
}


drops {
    #  [default: [harvestcraft:cactusfruititem], [minecraft:cactus]]
    S:aridGarden <
        harvestcraft:cactusfruitItem
     >

    #  [default: [harvestcraft:raspberryitem], [harvestcraft:oatsitem], [harvestcraft:ryeitem], [harvestcraft:celeryitem], [harvestcraft:peasitem], [harvestcraft:beetitem], [harvestcraft:rutabagaitem], [harvestcraft:broccoliitem], [harvestcraft:caulifloweritem], [harvestcraft:cabbageitem], [harvestcraft:spinachitem], [harvestcraft:cottonitem]]
    S:frostGarden <
        harvestcraft:raspberryItem
        harvestcraft:oatsItem
        harvestcraft:ryeItem
        harvestcraft:celeryItem
        harvestcraft:peasItem
        harvestcraft:beetItem
        harvestcraft:rutabagaItem
        harvestcraft:broccoliItem
        harvestcraft:cauliflowerItem
        harvestcraft:cabbageItem
        harvestcraft:spinachItem
        harvestcraft:cottonItem
     >

    #  [default: [harvestcraft:whitemushroomitem], [harvestcraft:blackberryitem], [harvestcraft:zucchiniitem], [harvestcraft:radishitem], [harvestcraft:rhubarbitem], [harvestcraft:tealeafitem], [harvestcraft:garlicitem], [harvestcraft:sweetpotatoitem], [harvestcraft:turnipitem], [harvestcraft:spiceleafitem], [harvestcraft:beanitem], [harvestcraft:leekitem], [harvestcraft:scallionitem], [harvestcraft:tomatoitem], [harvestcraft:cottonitem]]
    S:shadedGarden <
        harvestcraft:whitemushroomItem
        harvestcraft:blackberryItem
        harvestcraft:zucchiniItem
        harvestcraft:radishItem
        harvestcraft:rhubarbItem
        harvestcraft:tealeafItem
        harvestcraft:garlicItem
        harvestcraft:sweetpotatoItem
        harvestcraft:turnipItem
        harvestcraft:spiceleafItem
        harvestcraft:beanItem
        harvestcraft:leekItem
        harvestcraft:scallionItem
        harvestcraft:tomatoItem
        harvestcraft:cottonItem
     >

    #  [default: [harvestcraft:brusselsproutitem], [harvestcraft:spiceleafitem], [harvestcraft:blueberryitem], [harvestcraft:asparagusitem], [harvestcraft:cranberryitem], [harvestcraft:riceitem], [harvestcraft:seaweeditem], [harvestcraft:waterchestnutitem], [harvestcraft:okraitem], [harvestcraft:cottonitem]]
    S:soggyGarden <
        harvestcraft:brusselsproutItem
        harvestcraft:spiceleafItem
        harvestcraft:blueberryItem
        harvestcraft:asparagusItem
        harvestcraft:cranberryItem
        harvestcraft:riceItem
        harvestcraft:seaweedItem
        harvestcraft:waterchestnutItem
        harvestcraft:okraItem
        harvestcraft:cottonItem
     >

    #  [default: [harvestcraft:grapeitem], [harvestcraft:pineappleitem], [harvestcraft:kiwiitem], [harvestcraft:sesameseedsitem], [harvestcraft:curryleafitem], [harvestcraft:bambooshootitem], [harvestcraft:cantaloupeitem], [harvestcraft:gingeritem], [harvestcraft:coffeebeanitem], [harvestcraft:soybeanitem], [harvestcraft:eggplantitem], [harvestcraft:cottonitem]]
    S:tropicalGarden <
        harvestcraft:grapeItem
        harvestcraft:pineappleItem
        harvestcraft:kiwiItem
        harvestcraft:sesameseedsItem
        harvestcraft:curryleafItem
        harvestcraft:bambooshootItem
        harvestcraft:cantaloupeItem
        harvestcraft:gingerItem
        harvestcraft:coffeebeanItem
        harvestcraft:soybeanItem
        harvestcraft:eggplantItem
        harvestcraft:cottonItem
     >

    #  [default: [harvestcraft:strawberryitem], [harvestcraft:barleyitem], [harvestcraft:cornitem], [harvestcraft:cucumberitem], [harvestcraft:wintersquashitem], [harvestcraft:mustardseedsitem], [harvestcraft:onionitem], [harvestcraft:parsnipitem], [harvestcraft:peanutitem], [minecraft:potato], [minecraft:carrot], [harvestcraft:lettuceitem], [harvestcraft:artichokeitem], [harvestcraft:bellpepperitem], [harvestcraft:chilipepperitem], [minecraft:wheat], [harvestcraft:cottonitem]]
    S:windyGarden <
        harvestcraft:strawberryItem
        harvestcraft:barleyItem
        harvestcraft:cornItem
        harvestcraft:cucumberItem
        harvestcraft:wintersquashItem
        harvestcraft:mustardseedsItem
        harvestcraft:onionItem
        harvestcraft:parsnipItem
        harvestcraft:peanutItem
        minecraft:potato
        minecraft:carrot
        harvestcraft:lettuceItem
        harvestcraft:artichokeItem
        harvestcraft:bellpepperItem
        harvestcraft:chilipepperItem
        minecraft:wheat
        harvestcraft:cottonItem
     >
}


enablebeehivegeneration {
    B:beekeeping=true
}


"fruit trees" {
    B:almondtreeGeneration=true
    B:appletreeGeneration=true
    B:apricottreeGeneration=true
    B:avocadotreeGeneration=true
    B:bananatreeGeneration=true
    B:cashewtreeGeneration=true
    B:cherrytreeGeneration=true
    B:chestnuttreeGeneration=true
    B:cinnamontreeGeneration=true
    B:coconuttreeGeneration=true
    I:coniferousfruittreeRarity=1
    B:datetreeGeneration=true
    B:dragonfruittreeGeneration=true
    B:duriantreeGeneration=true
    B:figtreeGeneration=true

    # Default: 25, Lower is faster
    I:fruitGrowthSpeed=25
    B:gooseberrytreeGeneration=true
    B:grapefruittreeGeneration=true
    B:lemontreeGeneration=true
    B:limetreeGeneration=true
    B:mangotreeGeneration=true
    B:mapletreeGeneration=true
    B:nutmegtreeGeneration=true
    B:olivetreeGeneration=true
    B:orangetreeGeneration=true
    B:papayatreeGeneration=true
    B:paperbarktreeGeneration=true
    B:peachtreeGeneration=true
    B:peartreeGeneration=true
    B:pecantreeGeneration=true
    B:peppercorntreeGeneration=true
    B:persimmontreeGeneration=true
    B:pistachiotreeGeneration=true
    B:plumtreeGeneration=true
    B:pomegranatetreeGeneration=true
    B:rightclickharvestFruit=true
    B:rightclickmatureshowfruitHearts=false
    B:spiderwebtreeGeneration=true
    B:starfruittreeGeneration=true
    I:temperatefruittreeRarity=1
    I:tropicalfruittreeRarity=1
    B:vanillabeantreeGeneration=true
    B:walnuttreeGeneration=true
}


gardens {
    B:enablearidgardenGeneration=true
    B:enableberrygardenGeneration=true
    B:enabledesertgardenGeneration=true
    B:enablefrostgardenGeneration=true
    B:enablegardenSpread=true
    B:enablegourdgardenGeneration=true
    B:enablegrassgardenGeneration=true
    B:enablegroundgardenGeneration=true
    B:enableherbgardenGeneration=true
    B:enableleafygardenGeneration=true
    B:enablemushroomgardenGeneration=true
    B:enableshadedgardenGeneration=true
    B:enablesoggygardenGeneration=true
    B:enablestalkgardenGeneration=true
    B:enabletextilegardenGeneration=true
    B:enabletropicalgardenGeneration=true
    B:enablewatergardenGeneration=true
    B:enablewindygardenGeneration=true
    I:gardenRarity=2

    # Garden spread rate. 100 means a garden spawns every tick. 1 means a garden spawns with a probability of 1% per tick. [range: 1 ~ 100, default: 30]
    I:gardenSpreadRate=30
    I:gardendropAmount=3
    B:gardensdropSeeds=false
    I:gardenspreadMax=8
    I:gardenspreadRate=100
}


general {
    # Default: 3600 or 3 minutes
    I:buffTimeForTopTier=3600

    # Enables harvesting by right-clicking. [default: true]
    B:enableEasyHarvest=true

    # Enables catching of HarvestCraft fish using the normal fishing rod. [default: true]
    B:enableHCFish=true

    # Makes changes to vanilla food item and drop hunger restore and saturation values to be balanced with HarvestCraft food. [default: true]
    B:enablevanillafoodBalance=true
    I:saltrecipeAmount=1
    B:sheepdropMutton=true

    # Enable to have raw calamari smelt into cooked fish instead. [default: false]
    B:smeltsquidintocookedFish=false

    # Enables squid mobs to drop raw calamari. [default: true]
    B:squiddropCalamari=true

    # Default: 10, Choose 5, 6, 7, 8, 9, or 10 shank foods which become top tier.  Foods at this level or above give buffs.  Top tier foods are always edible, so be careful!  Set to 0 to have no top tier foods.
    I:topTierFood=10
}


"market currency" {
    S:ignore=ignore
    S:ignore2=ignore
    S:ignore3=ignore
    I:marketcurrencyBees=0
    I:marketcurrencyBonemeal=0
    I:marketcurrencyChicken=0
    I:marketcurrencyCow=0
    I:marketcurrencyFish=0
    I:marketcurrencyHorse=0
    I:marketcurrencyLead=0
    I:marketcurrencyLlama=0
    I:marketcurrencyMeat=0
    I:marketcurrencyNametag=0
    I:marketcurrencyOcelot=0
    I:marketcurrencyPig=0
    I:marketcurrencyRabbit=0
    I:marketcurrencySeeds=0
    I:marketcurrencySheep=0
    I:marketcurrencyWolf=0
    I:marketcurrencyconiferousSaplings=0
    I:marketcurrencytemperateSaplings=0
    I:marketcurrencytropicalSaplings=0
}


"market prices" {
    I:marketbonemealPrice=3
    I:marketchickenPrice=3
    I:marketcowPrice=9
    I:markethorsePrice=12
    I:marketleadPrice=1
    I:marketllamaPrice=12
    I:marketnametagPrice=1
    I:marketocelotPrice=9
    I:marketpigPrice=6
    I:marketqueenbeePrice=3
    I:marketrabbitPrice=3
    I:marketsaplingPrice=3
    I:marketseedPrice=1
    I:marketsheepPrice=6
    I:marketwolfPrice=9
}


"market sales" {
    B:marketsellBonemeal=true
    B:marketsellChicken=true
    B:marketsellCow=true
    B:marketsellHorse=true
    B:marketsellLead=true
    B:marketsellLlama=true
    B:marketsellNametag=true
    B:marketsellOcelot=true
    B:marketsellPig=true
    B:marketsellQueenbee=true
    B:marketsellRabbit=true
    B:marketsellSeeds=true
    B:marketsellSheep=true
    B:marketsellWolf=true
    B:marketsellconiferousSaplings=true
    B:marketselltemperateSaplings=true
    B:marketselltropicalSaplings=true
}


"miscellaneous recipes" {
    B:enablecropitemsasseeds=true
    B:enablecroptoseedRecipe=true
    B:enableharvestcraftfish=true
    B:enablelistAllwaterfreshwater=true
    B:enablelistAllwatervanillawaterbucket=true
    B:enablesaltfromwaterbucketrecipe=true
    B:enabletofuasmeatinRecipes=true
    B:enabletofuasmilkinRecipes=true
    I:fishtrapbaitrecipeamount=4
    I:freshmilkfrombucket=4
    I:freshwaterfrombucket=1
    I:fruitbaitrecipeamount=4
    I:grainbaitrecipeamount=4
    I:marketblockrecipeItem=0
    I:veggiebaitrecipeamount=4
}


salt {
    B:enablesaltGeneration=true
    I:saltRarity=30
}


seeds {
    B:artichokeseeddropfromgrass=false
    B:asparagusseeddropfromgrass=false
    B:bambooshootseeddropfromgrass=false
    B:barleyseeddropfromgrass=false
    B:beanseeddropfromgrass=false
    B:beetseeddropfromgrass=false
    B:bellpepperseeddropfromgrass=false
    B:blackberryseeddropfromgrass=false
    B:blueberryseeddropfromgrass=false
    B:broccoliseeddropfromgrass=false
    B:brusselsproutseeddropfromgrass=false
    B:cabbageseeddropfromgrass=false
    B:cactusfruitseeddropfromgrass=false
    B:candleberryseeddropfromgrass=false
    B:cantaloupeseeddropfromgrass=false
    B:cauliflowerseeddropfromgrass=false
    B:celeryseeddropfromgrass=false
    B:chilipepperseeddropfromgrass=false
    B:coffeeseeddropfromgrass=false
    B:cornseeddropfromgrass=false
    B:cottonseeddropfromgrass=false
    B:cranberryseeddropfromgrass=false
    B:cucumberseeddropfromgrass=false
    B:curryleafseeddropfromgrass=false
    B:eggplantseeddropfromgrass=false
    B:garlicseeddropfromgrass=false
    B:gingerseeddropfromgrass=false
    B:grapeseeddropfromgrass=false
    B:kiwiseeddropfromgrass=false
    B:leekseeddropfromgrass=false
    B:lettuceseeddropfromgrass=false
    B:mustardseeddropfromgrass=false
    B:oatsseeddropfromgrass=false
    B:okraseeddropfromgrass=false
    B:onionseeddropfromgrass=false
    B:parsnipseeddropfromgrass=false
    B:peanutseeddropfromgrass=false
    B:peasseeddropfromgrass=false
    B:pineappleseeddropfromgrass=false
    B:radishseeddropfromgrass=false
    B:raspberryseeddropfromgrass=false
    B:rhubarbseeddropfromgrass=false
    B:riceseeddropfromgrass=false
    B:rutabagaseeddropfromgrass=false
    B:ryeseeddropfromgrass=false
    B:scallionseeddropfromgrass=false
    B:seaweedseeddropfromgrass=false
    I:seedrarity=1
    B:sesameseedsseeddropfromgrass=false
    B:soybeanseeddropfromgrass=false
    B:spiceleafseeddropfromgrass=false
    B:spinachseeddropfromgrass=false
    B:strawberryseeddropfromgrass=false
    B:sunflowerseeddropfromgrass=false
    B:sweetpotatoseeddropfromgrass=false
    B:teaseeddropfromgrass=false
    B:tomatoseeddropfromgrass=false
    B:turnipseeddropfromgrass=false
    B:waterchestnutseeddropfromgrass=false
    B:whitemushroomseeddropfromgrass=false
    B:wintersquashseeddropfromgrass=false
    B:zucchiniseeddropfromgrass=false
}


"shipping bin prices" {
    I:shippingbinbeesPrice=16
    I:shippingbincropPrice=32
    I:shippingbinfishPrice=16
    I:shippingbinmeatPrice=16
}


"shipping bin purchases" {
    B:shippingbinbuyBees=true
    B:shippingbinbuyCrops=true
    B:shippingbinbuyFish=true
    B:shippingbinbuyMeat=true
    B:shippingbinenablevanillaMCBees=true
    B:shippingbinenablevanillaMCCrops=true
    B:shippingbinenablevanillaMCEgg=true
    B:shippingbinenablevanillaMCFish=true
    B:shippingbinenablevanillaMCMeat=true
    B:shippingbinenablevanillaMCMonsterParts=true
}

**Comment by annasoaps** [comment] 2018-02-18 12:58
UPDATE! It works! 
Thanks to your comment about the config files Deshiba. It made me think that maybe there is something in the config file from harvestcraft, because I have been playing with that mod since the dawn of times but never looked at the config. So I thought that maybe there was some setting from way back when that is conflicting now. So I moved the config files from the minecraft folder and started a new world, and now it works Weeeeee.

Thank you!!

**Comment by Deshiba** [comment] 2018-02-18 13:05
You are welcome. Could you close the issue?

**Closed** 2018-02-18 13:06 UTC
Labels: investigating
