### ISSUE TITLE
Animania animals won't spawn in modded biomes when 'replaceVanilla(Animals)' are set false

### ISSUE THREAD

**Issue by YswMusician** [capnkirok/animania#464] opened 2017-11-30 10:18 UTC
### Expected Behavior
Animania animals spawn in modded biomes(Biomes O' Plenty, for example) when  'replaceVanilla(Animals)' are set false. ('spawnAnimania(Animals)' are left true, which is default.)

### Actual Behavior
No single animania animals in modded biomes, when configs are set as mentioned above.
Since Biomes O' Plenty makes vanilla biomes rare, animania animals also become very rare.

I ran some tests.
First, I ran test without biomes o' plenty, and both animals are spawned equally(actually, vanilla animals were spawned more frequently).
And, I installed new Minecraft instance with Animania, Biomes O' Plenty and some dependencies.
I found tons of animania animals in Taiga, Desert and Extreme Hills, which are vanilla biomes. But no single animals but only vanilla animals in Coniferous Forest and Maple Woods, which are from Biomes o' Plenty.

### Steps to Reproduce
Install Biomes o' Plenty, Animania and its dependencies(of course).
Set animania config: Set 'replaceVanilla(Animals)' as false, leave 'spawnAnimania(Animals)' as true.
Create world with Biomes o' Plenty and check out modded biomes.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.11.2, Animania 1.11.2-1.4.2, Single Player.

**Comment by capnkirok** [comment] 2017-12-01 21:54
Ok, just tested this and it's working as intended. Also all spawns are in BiomeDictionary, for example:
![image](https://user-images.githubusercontent.com/9628379/33505119-725aa768-d6ea-11e7-9cbf-292855b98b17.png)

If you do turn off 'Replace', keep in mind that you are eliminating a large percentage of Animania spawns from the world. That means you would need to 'turn up' the frequency of the Animania spawns to compensate.

**Comment by capnkirok** [comment] 2017-12-01 21:56
Visual evidence of Animania animals spawning in BOP biomes:

![2017-12-01_22 52 03](https://user-images.githubusercontent.com/9628379/33505196-b17bafdc-d6ea-11e7-8b94-ed0e6ea1dfd6.png)

**Comment by capnkirok** [comment] 2017-12-01 21:57
Visual evidence of animals spawning in BOP biome:
![2017-12-01_22 50 37](https://user-images.githubusercontent.com/9628379/33505262-fa328fa2-d6ea-11e7-8435-73dba467e7ba.png)

**Comment by capnkirok** [comment] 2017-12-01 21:58
So... recommend you turn some settings up on spawn probabilities and try again. And let me know!

**Comment by capnkirok** [comment] 2017-12-02 09:50
Hey @YswMusician I just did more testing this morning and everything is working as intended. Try my tip of increasing spawn probability (to something like 10+) for the animals you want to see more of.

**Comment by YswMusician** [comment] 2017-12-03 04:22
That's strange. I increased spawn probability 10 times and results were really frustrating.
I used SuperFlat world with Overworld preset to test animal spawning and here's results. All I changed is biome ID, and nothing else is different.

Vanilla Minecraft Biomes:
![2017-12-03_12 44 18](https://user-images.githubusercontent.com/23522120/33522292-9675ac22-d82c-11e7-84b2-d9ea7e9f0004.png)
![2017-12-03_12 44 25](https://user-images.githubusercontent.com/23522120/33522293-96a5b19c-d82c-11e7-8480-69e23dd72a61.png)
![2017-12-03_13 18 02](https://user-images.githubusercontent.com/23522120/33522294-96d4d256-d82c-11e7-8150-70af72b5b730.png)
![2017-12-03_13 18 13](https://user-images.githubusercontent.com/23522120/33522295-97045dc8-d82c-11e7-8a31-eb9ff7970414.png)

Biomes O' Plenty Biomes:
![2017-12-03_12 40 31](https://user-images.githubusercontent.com/23522120/33522297-a327b6e0-d82c-11e7-93a4-b22a70e88f97.png)
![2017-12-03_12 49 47](https://user-images.githubusercontent.com/23522120/33522298-a35b0c5c-d82c-11e7-9523-c583845d18e2.png)
![2017-12-03_13 09 31](https://user-images.githubusercontent.com/23522120/33522299-a38b705e-d82c-11e7-9b56-1e1a5d25d2a0.png)

As these screenshot suggests, even though spawn probability is increased, this change only effects vanilla biomes.
This is very minor problem, and may be on low priority. But this problem was quite troublesome for me, and I hope this to be fixed. Thanks :)

**Comment by capnkirok** [comment] 2017-12-03 08:32
Just to eliminate any variables... what version of BOP are you using?

**Comment by capnkirok** [comment] 2017-12-03 09:00
I also increased Number of families and also probability, and I saw what you saw. Increased numbers of Animania animals in vanilla biomes. Then I wondered if forcing BOP to load before Animania made a difference. I believe it did :)

So, this must be fixed in the code... so you'll have to wait for the update in the next couple of days.

![2017-12-03_09 57 30](https://user-images.githubusercontent.com/9628379/33523836-be8d7ee0-d810-11e7-8068-0cb959019186.png)

**Comment by YswMusician** [comment] 2017-12-04 10:06
Thank you very much!
Here's detail about Minecraft Instance I used in testing, in case you need:
Minecraft 1.11.2 / forge-13.20.1.2530
Animania 1.11.2-1.4.2
Biomes O' Plenty 1.11.2-6.2.0.2254 (With default config)
CraftStudioAPI 0.3.0.86(beta)

**Closed** 2017-12-12 09:08 UTC
Labels: 1.10.2, 1.11.2, 1.12, compat, fixed in next release
