### ISSUE TITLE
Truffle soup crash

### ISSUE THREAD

**Issue by Kearthar** [capnkirok/animania#222] opened 2017-06-12 22:37 UTC
https://pastebin.com/ar7ejagU
Here is the crashlog I got when I drank some truffle soup, caused instantaneous crashing

**Comment by Tschipp** [comment] 2017-06-13 05:13
Thanks, shouls be easy enough to fix

**Comment by Tschipp** [comment] 2017-06-13 05:41
I'm not able to recreate this. I've tried eating every food and nothing unusal happens. You are using an outdated version, but I don't think that's the cause of this, we haven't touched food in ages. Can you describe exactly what happened? Did you have any other status effects on yourself?

**Comment by Kearthar** [comment] 2017-06-13 07:05
it was in the raxpack 2 using version 1.1.4 of animania me and another person had the issue

**Comment by capnkirok** [comment] 2017-06-18 16:32
Ok after doing some searching, it looks like it could be a bug in AppleCore. Can you remove AppleCore and do a test? If so, can you post on their github? I see multiple references to this issue on the Interwebs.

**Comment by Tschipp** [comment] 2017-06-23 22:42
Gonna close this next week if we don't hear back

**Comment by Kearthar** [comment] 2017-06-24 19:26
Yeah it was apple core that caused it. I've been busy and haven't touched minecraft in a while

**Comment by capnkirok** [comment] 2017-06-27 20:49
Thanks!

**Closed by capnkirok** 2017-06-27 20:49 UTC
Labels: invalid
