### ISSUE TITLE
[1.10.2] Crash with placing glass in a crafting table in a recipe which is not a recipe.

### ISSUE THREAD

**Issue by b0bst3r** [capnkirok/animania#32] opened 2017-02-27 02:28 UTC
So this happens with the old 0.9.8 BETA and with the latest 1.0.0 we just never caught what was causing the crashes as the crash is generic and mentions no mods.

The crash - http://pastebin.ubuntu.com/24075849/

Now this happened in a pack of mods but you can see by the above crash log that just your mod and JEI are present, I narrowed it down to Animania then confirmed it by running just the 2 mods.

To repeat:
 - get a vanilla crafting table (or any crafting table)
 - get 8 vanilla glass blocks
 - place the 8 blocks in a circle in the crafting table

Upon placing the 8th block in the crafting table the above crash occurs.

As to why I haven't a clue because there is no recipe with 8 glass around the outside and the middle empty.

We are getting various other crashes too which maybe related or not with recipes but the one above is reproducible.

Additional info - for making stained glass you place the 8 glass in a circle and a dye in the middle, if you place the dye first and then the glass it still *does* crash.

**Comment by capnkirok** [comment] 2017-02-27 06:36
That is really, really odd. I saw this in my console during testing, but assumed it was just JEI, since there is no recipe like this at all in Animania. Will look further into it.

**Comment by Thyriel** [comment] 2017-02-27 07:18
http://pastebin.com/QA9pmPB8
I can confirm that strange crash. Happens with only animania and no other mods (not even JEI)

**Comment by brblostmycrayons** [comment] 2017-02-27 17:51
hi, i just wanted to confirm i have had this happen to me as well! i had a purple dye in the center and tried to dye vanilla glass with it and upon placing the last piece of glass i crashed. as someone placed the glass in a circle with an empty center i suppose it means there's a problem with the glass specifically and not the dye like i thought lol  

looking forward to updated mod to fix this and the mobs unable to spawn in premade world, as well!

**Comment by capnkirok** [comment] 2017-02-27 18:16
Ok, this is fixed in Dev, and will be released in 1.0.1. Was an old recipe I forgot to turn off (for the Hamster Ball). Thanks.

**Closed** 2017-03-01 23:31 UTC
Labels: bug, fixed in dev
