### ISSUE TITLE
Bucket Dupe: Slop

### ISSUE THREAD

**Issue by Grayvs** [capnkirok/animania#22] opened 2017-02-23 07:49 UTC
When crafting Slop you get a second separate bucket of Slop instead of giving you an empty bucket back.

**Comment by capnkirok** [comment] 2017-02-23 09:18
Thanks! will fix!

**Comment by capnkirok** [comment] 2017-02-23 16:14
Can you share with me a screenshot of your recipe and result? I can't reproduce.

**Comment by capnkirok** [comment] 2017-02-27 21:16
Going to close this unless I hear back, cannot reproduce this one.

**Comment by JamRobLam** [comment] 2017-05-05 22:09
can this be opened back up? 
i also found a bucket dupe however im not sure if the recipe is added by you guys or the pack designer.
im using Animania 1.0.4.7, mincraft 1.11.2, in the Modded Mischief II pack. 

https://drive.google.com/open?id=0B_GugIbytyFYYkYzRW5IdVVjNjQ

**Comment by Tschipp** [comment] 2017-05-05 22:35
yeah, I'll look into it

**Comment by Tschipp** [comment] 2017-05-06 17:47
Fixed in dev

**Closed** 2017-05-28 23:40 UTC
Labels: 1.10.2, 1.11.2, bug, confirmed, fixed in next release
