### ISSUE TITLE
Inconsistent breeding behavior between sheep and cows

### ISSUE THREAD

**Issue by MauveCloud** [capnkirok/animania#528] opened 2018-01-24 17:10 UTC
### Expected Behavior
Breeding as in description:
"Animals will only breed or drop their top resources when they are happy"
Thus my sheep, which are almost all "Well-Fed", should be breeding, but my cows, which are all at least thirsty (since I have intentionally deprived them of water), should stop breeding.

### Actual Behavior
Sheep breed once if at all, then stop, even in an ideal environment - lots of grass for them to eat and a modest man-made pond for them to drink from.  Overlay from TheOneProbe shows nearly all of them "Well-Fed"
I still see calves appearing in my cow pasture, indicating they're still breeding, despite all being thirsty and some hungry.

### Steps to Reproduce
1. Build a cow pasture and a sheep pasture - I built my cow pasture from (220, 62, 220) to (240, 62, 240) and my sheep pasture from (190, 62, 220) to (210, 62, 240) with grass fill, dark oak fences around them one layer up (using the Fence Jumper mod to get in and out), and a 4x4 pond near the NW corner of each.  I had seed: -3923336132183675415
2. Collect breeding stock - I got a Friesian cow and bull, a Merino ram, and a Dorset ewe (and later a few more Merino and Dorset sheep) using the Golden Lasso from Extra Utilities 2 (since the AI for following food is apparently unreliable; using a lead as suggested in the description would probably also work, though)
3. Give them a while to breed.
4. Once the cows start getting crowded, fill in the pond in the cow pasture.
5. Wait some more in vain hope for the sheep to breed. (and notice that the cows continue to breed)

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.10.2, Forge 12.18.3.2511, Animania 1.4.4, Survival Single Player (peaceful)
(I can provide a full list of mods if requested)

### Screenshots encouraged
![2018-01-24_08 17 40](https://user-images.githubusercontent.com/8942955/35345172-cc0b977c-00e3-11e8-9b48-5e79e2ad3b44.png)
![2018-01-24_08 17 50](https://user-images.githubusercontent.com/8942955/35345183-d4c421ae-00e3-11e8-903a-7210ecee155c.png)

**Comment by capnkirok** [comment] 2018-01-24 18:13
Nice write up. A perfectly formed issue, thank you!

But... well, the code is exactly the same for all mammal breeds (and I just tested as well, and it's working as intended). So... how can I explain this :)

Proximity is also a factor. The two animals need to be very close to each other (< 2 blocks). So if you have a wide open space like that... they might not find each other as much.

There is also just random chance. They loop their AI repeatedly, and are not always checking for the nearest mate... when the opportunity strikes. Again, to add realism.

You can test this yourself. Recommend you try adding a lead to the male and female you are trying to mate and walk them close to each other (while they are well fed) and seeing how it works.

**Comment by MauveCloud** [comment] 2018-01-24 19:18
I've put two of the sheep in a smaller pasture with grass and water (and I'm not happy about this requirement - it seems cruel to put sheep in such a small pasture), and will give them more time.  They were both "Well-fed" when I moved them, but the ewe seems to be on sort of a hunger strike now (i.e. hungry, yet not eating, despite there being several grass blocks nearby), while the ram seems to be eating grass more often than he probably needs to, which is confusing.

However, you haven't explained the other part - if I understood the mod description correctly, thirsty cows should _not_ still be breeding.  They've been thirsty for at least 10 hours real-time (probably more), so the calves that are visible in the screenshot must have been born due to cows breeding despite their thirst.

**Comment by MauveCloud** [comment] 2018-01-24 21:28
Update: with the sheep in a smaller enclosure as in this screenshot:
![2018-01-24_13 18 25](https://user-images.githubusercontent.com/8942955/35357753-57ee3fd6-0109-11e8-98e7-cd8b2b61db94.png)
Even after letting the game run for over 2 hours, they still haven't produced a lamb.

I've switched to a different strategy to get my cows to stop breeding - I've separated the bulls from the cows, but TOP won't show me whether my calves are male or female, so when I came back after lunch, there were some bulls in with the cows and some new calves.

**Comment by capnkirok** [comment] 2018-01-24 22:27
Yeah, I don't know what's wrong with your Sheep, but this is what I get after about 10 seconds.

[![Screenshot from Gyazo](https://gyazo.com/de2ed14cd986d923d415f5f609aa7cc8/raw)](https://gyazo.com/de2ed14cd986d923d415f5f609aa7cc8)

**Comment by capnkirok** [comment] 2018-01-24 22:35
Also, the animals can 'mate' if they are hungry or thirsty. But they will not give birth. Sorry if that's not clear in the Overview.

Recommend you try the 'lead' trick. Spawn a male and female, keep them very close with a lead and see if they breed. For me this usually takes less than 30 seconds. Try it in a test world. If they do breed, then we know it's a proximity issue. If they don't we know it's something else (which would be weird).

I also don't like tight fences either, that's not what I was suggesting how you should play the game :)

One solution I can think of is to expand the search distance for mates, maybe put that in the config (thought this pen is more than enough space).

Let me know the results of your lead test.

**Comment by MauveCloud** [comment] 2018-01-24 23:28
The lead trick worked in a creative superflat world - they mated pretty quick, and I was even able to confirm with a creative probe that the ewe was pregnant.

However, that was with freshly spawned sheep and using a lead, so I'm not so sure this is a simple proximity issue.  Digging deeper with jd-gui, I discovered that EntityCowBase has some code that checks "dryTimerCow" and sets "fertile" true under certain conditions (presumably a variable delay after giving birth).  EntityEweBase has no analogous check, despite having a field called "dryTimerEwe", meaning that ewes become permanently barren after their first mating.

As far as animals not giving birth when hungry or thirsty, I think the presence of calves in the screenshots I posted before contradicts that claim.

**Comment by BryanBoru** [comment] 2018-01-26 16:13
I don't know if this is related or not, but My current world, which once had chickens, never has chickens anymore since updating as well. If Anyone likes I can give more information, but I am unsure if this is related or not.

**Comment by capnkirok** [comment] 2018-01-26 22:39
@BryanBoru can you post that in another issue?

**Comment by capnkirok** [comment] 2018-01-26 22:40
@MauveCloud ok, let me check that.. you may be onto something.

**Comment by MauveCloud** [comment] 2018-01-31 21:29
After discovering #539, I'm less certain that the calves' presence proves that the cows were mating and giving birth despite being thirsty.

**Comment by capnkirok** [comment] 2018-01-31 23:12
Ahh! Ok, but will still look at the dryTimerEwe.

**Comment by capnkirok** [comment] 2018-02-04 23:19
Yes, dryTimerEwe was not resetting on 1.10. Fixed in next release.

**Comment by capnkirok** [comment] 2018-02-04 23:27
And 1.11....

**Closed** 2018-02-05 00:16 UTC
Labels: 1.10.2, 1.11.2, bug, fixed in next release

**Comment by MauveCloud** [comment] 2018-02-05 04:09
Confirmed fixed in 1.10.2.  However, as you might have noticed from my comments in other issues, my focus has shifted to playing 1.12.2.

**Comment by capnkirok** [comment] 2018-02-05 08:12
Ok, great.
