### ISSUE TITLE
Default spawn rates are somehow, still too high

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#62] opened 2017-03-18 23:43 UTC
https://www.dropbox.com/s/7og1pk6pyo4yg4t/Screenshot%202017-03-18%2019.41.57.png?dl=0

What even. This is on 1.0.3, BTW.

**Comment by capnkirok** [comment] 2017-03-19 00:11
Can you post your modlist? Will check for conflicts...

Also, you might need to cull out old entities and start  up again...

PC

**Comment by Sunconure11** [comment] 2017-03-19 00:42
That was in a new world.

Also, this is my modlist:

http://www.modlister.com/user/Sunconure11

**Comment by capnkirok** [comment] 2017-03-19 14:45
Ok, def. something weird going on (like a conflict). What mod is it that shows the entity totals?

**Comment by capnkirok** [comment] 2017-03-19 14:49
Also... what are your 'spawn' settings in the config and your current 'game rule' settings...?

**Comment by Sunconure11** [comment] 2017-03-19 15:08
CoFHCore shows entity counts when mobs are killed.

Settings are untouched for configuration, but I will dig them up in a bit anyways.

No game rules are on, this is a new world.

**Comment by capnkirok** [comment] 2017-03-19 15:23
Well, if you had a previous version of the config, you should reset it to default (or delete it). They don't reset unless you do that or manually change them.

If this still shows way to many mobs.... set 'replace vanilla cows/sheep/pigs' configs to false and let me know the count again. There may be some mod thats spawning additional vanilla... (which then get converted to Animania)

**Comment by Sunconure11** [comment] 2017-03-19 15:48
Spawn rate is not as high as before after resetting the configs. However, I am using Biomes O' Plenty, which often has biomes with multiple biomedictionary definitions.

https://www.dropbox.com/s/tyrjrre09lnuef9/Screenshot%202017-03-19%2011.47.52.png?dl=0

This was taken in a separate world though.

**Comment by Sunconure11** [comment] 2017-03-19 15:49
And now its starting to spike:

https://www.dropbox.com/s/lg2815qfmokln62/Screenshot%202017-03-19%2011.49.03.png?dl=0

**Comment by capnkirok** [comment] 2017-03-19 16:08
Yes, was aware of BOP. Was planned in. Ok, if you still have patience, can you test the following:

Test 1: In the Animania config, go to 'game rules' and change the 'Remove vanilla (pigs/chickens/cows)' and set to False. Then restart and see if you get 'spikes' and let me know.

Test 2: Create a new world with just Animania and BOP, COFH and see if you get ridiculous spawning? This will confirm the conflict.

**Comment by Sunconure11** [comment] 2017-03-19 17:21
https://www.dropbox.com/s/4298kfy3c6r9bns/Screenshot%202017-03-19%2013.18.02.png?dl=0 Without said settings

With said settings: https://www.dropbox.com/s/pft3q4xjgsok6dk/Screenshot%202017-03-19%2013.21.12.png?dl=0

**Comment by Sunconure11** [comment] 2017-03-19 17:28
https://www.dropbox.com/s/68nsy1zipfzcamx/Screenshot%202017-03-19%2013.28.15.png?dl=0

Inconclusive

**Comment by capnkirok** [comment] 2017-03-19 17:42
That is just a ton of entities. Bizarre. Thanks so much. I'm going to tool around with this a bit.

I assume with just Animania and nothing else you get a reasonable number of entities?

**Comment by Sunconure11** [comment] 2017-03-19 17:48
I haven't tried that, I tested with BoP, CoFHCore (to kill the mobs), and JEI (because thats pretty much required).

**Comment by Sunconure11** [comment] 2017-03-19 17:48
I also tested with my major setup and still get similar readings.

**Comment by Sunconure11** [comment] 2017-03-19 17:52
Also, you might want to look into other mods that add their own biomes, such as Ars Magica 2.

**Comment by capnkirok** [comment] 2017-03-19 17:54
Will do.

**Comment by capnkirok** [comment] 2017-03-19 18:06
I think you may be correct about the spawns. I think it's double/triple adding based on BiomeDictionary.

**Comment by capnkirok** [comment] 2017-03-19 19:18
Yes, this is what's happening. Sigh. I never noticed this until now. I *think* vanilla MC biomes are not registered in BiomeDictionary, which is why it doesn't appear until you add a mod that does create new biomes that are listed....

**Comment by capnkirok** [comment] 2017-03-19 21:21
I'm able to replicate this. The main culprit (as you can see) are the Rodents (Ferrets, Hedgehogs). These are also the ones with multiple spawn listings using BiomeDictionary. The other populations are not too far off.

![image](https://cloud.githubusercontent.com/assets/9628379/24084812/8d7e792a-0cf1-11e7-80c1-0272ef573462.png)

Here's what I recommend:
- Reduce all spawn probabilities to say 8 or 10 in the config, except for Rodents... set that one to say 3
- Reduce max spawn size of rodents to 1
- Or if you want to, you can turn spawning of Rodents completely off.

Let me know the results. I think it will be much more reasonable. I will also change the Rodent spawns for 1.0.4

**Comment by Sunconure11** [comment] 2017-03-20 01:53
I did that, and got this:

https://www.dropbox.com/s/vn7c5ujd1qyu7ab/Screenshot%202017-03-19%2021.53.02.png?dl=0

**Comment by capnkirok** [comment] 2017-03-20 18:09
Yep, still the rodents are too high, but the rest are OK imo. I've already made the change in the code. I plan to push another version tonight, hopefully this does the trick.

**Comment by Sunconure11** [comment] 2017-03-21 02:11
https://www.dropbox.com/s/s7elme8a13hrxwg/Screenshot%202017-03-20%2022.10.13.png?dl=0

WHY DO YOU MOCK ME 1.0.4

**Comment by Sunconure11** [comment] 2017-03-21 02:11
I think you should take cues from Lycanites Mobs in terms of how to handle spawn configurations to some extent.

**Comment by capnkirok** [comment] 2017-03-21 06:52
I'll chat with Lycanite, good idea.

**Comment by capnkirok** [comment] 2017-03-21 07:01
I assume you deleted your config files?

**Comment by Sunconure11** [comment] 2017-03-21 16:29
Yes, I did.

**Comment by capnkirok** [comment] 2017-03-22 19:24
Ok, I'm going to hardcode spawn rates going forward... will have a release tonight.

**Comment by Sunconure11** [comment] 2017-03-23 18:02
https://www.dropbox.com/s/a8fyp1fg72u7ek6/Screenshot%202017-03-23%2014.00.50.png?dl=0

You might want to include reduced spawn rates in the config in a future update. I have no clue what is going on at this point. This happened in a Mega Taiga Hills.

However, your update seems to have stopped runaway spawning that caused TPS lag.

**Comment by Sunconure11** [comment] 2017-04-01 09:39
https://www.dropbox.com/s/pn4h7a2a56hxmcc/Screenshot%202017-04-01%2005.37.35.png?dl=0

Oh for fucks sake

**Comment by capnkirok** [comment] 2017-04-01 10:06
How is that even possible??!?

Is it the same for you standalone (with no other mods)?

**Comment by Sunconure11** [comment] 2017-04-01 10:21
It happened with basically the same setup as usual.

**Comment by capnkirok** [comment] 2017-04-02 21:45
@Sunconure11 do you have a download to your modpack? Would like to do some tests... save me some time downloading and setting up...

**Comment by Sunconure11** [comment] 2017-04-02 22:58
https://www.dropbox.com/s/0tgxzyvg70izvso/curse%20instance.zip?dl=0

**Comment by capnkirok** [comment] 2017-04-03 23:45
Ok, here's a release candidate 1.0.4.5. Plan to publish tomorrow after a bit more testing. Recommend you purge your config and try it out. You'll see new options in the config for spawn (all require restart). @Sunconure11 

https://www.dropbox.com/s/ejbhvez3wrb05bn/animania-1.10-1.0.4.5.jar?dl=0

**Comment by Sunconure11** [comment] 2017-04-04 00:41
Spawn rates are indeed far further down, and no longer batshit crazy. According to the /forge tps command, there still appear to be some TPS issues, but I'm not sure if that is this mod or another at this point.

**Comment by Sunconure11** [comment] 2017-04-04 01:13
Scratch that, it seems to climb the longer you are in a chunk. At first it starts out with a small amount.

https://www.dropbox.com/s/e66xvcftxqyt93z/Screenshot%202017-04-03%2021.13.06.png?dl=0

**Comment by capnkirok** [comment] 2017-04-04 05:38
Oh my goodness!! We got it! I know it doesn't look like it, but your graph revealed issues in my code with those particular entities. The others, where the code is fine, behaved as intended.

Will push another RC.

**Comment by capnkirok** [comment] 2017-04-04 18:31
https://www.dropbox.com/s/8w6xkxttbvreaeg/animania-1.10-1.0.4.5.jar?dl=0

**Comment by capnkirok** [comment] 2017-04-07 08:41
@Sunconure11 any update?

**Comment by Sunconure11** [comment] 2017-04-07 09:01
Still some TPS lag, but I'm not sure if it is related to this mod at this point. Like I mentioned though, I advise you sift through all mobs you have in the mod and see if they still suffer from the error you mention.

But the TPS is definitely better than before.

**Comment by capnkirok** [comment] 2017-04-07 09:24
Ok, great. TPS/Lag is flagged under the other issue, #71. I will leave that one open and close this, which is related to spawning rates. The lag issue is related to AI scripting, which should be much, much better, but will keep it open for further testing.

**Closed by capnkirok** 2017-04-07 09:24 UTC
Labels: compat, fixed in next release, question
