### ISSUE TITLE
Hamster GetIsTamed

### ISSUE THREAD

**Issue by PSILONCRAFT** [capnkirok/animania#536] opened 2018-01-29 21:01 UTC
### Expected Behavior

No client crash

### Actual Behavior

Client crashes server not affected

### Steps to Reproduce

download eye of the storm modpack

### Version of Minecraft, version of Animania, Single Player or Server

1.12.2 MC Animania 1.12.2-1.4.4 server

### Screenshots encouraged
[crash-2018-01-29_21.51.18-client.txt](https://github.com/capnkirok/animania/files/1675212/crash-2018-01-29_21.51.18-client.txt)

**Comment by capnkirok** [comment] 2018-01-29 21:41
More heap corruption and another dupe of #534

**Comment by capnkirok** [comment] 2018-01-29 21:42
Thanks for the post... I need to redo data for rodents (and all animals).

**Comment by Rikshy** [comment] 2018-02-09 19:35
I have the same issue, and to answer your question: i did

**Comment by capnkirok** [comment] 2018-02-17 16:09
See test link at bottom of this thread:
https://github.com/capnkirok/animania/issues/550

**Comment by BryanBoru** [comment] 2018-02-19 15:00
I lost my logs, so I never reported it, but I had an issue with primitive mobs and animania together kicking players from a dedicated server, The logs continuously referenced the hamster, I wonder if this was related.

**Comment by capnkirok** [comment] 2018-02-19 15:36
@BryanBoru thanks for the heads up. I will do some compat testing.

**Closed** 2018-02-20 05:41 UTC
Labels: duplicate, fixed in next release
