### ISSUE TITLE
Problem with the drops!

### ISSUE THREAD

**Issue by rjpangit132** [capnkirok/animania#279] opened 2017-07-18 23:04 UTC
when i kill the pigs in the mod it only drop raw porkchop and same with the cow but i look in the settings it is enabled the drops in the mod in version 1.10.2

**Comment by capnkirok** [comment] 2017-07-20 07:30
What version of Animania are you using?

**Comment by capnkirok** [comment] 2017-07-20 16:21
Ok, I just tested and it is working as intended. However.... Custom Drops only work with certain animals.... this ensures continuity with Vanilla.

Yorkshire Pig and Large Whites drop vanilla porkchops.
Holsteins and Friesians drops vanilla beef.

The rest drop the Custom Drops. Hope that solves your issue!

**Comment by capnkirok** [comment] 2017-07-20 16:46
Ok, this seems to be working in 1.10.2, but not in 1.11.2, so re-opened.

**Comment by capnkirok** [comment] 2017-07-23 19:08
Ok, now fixed in 1.11.2

**Closed** 2017-07-24 18:33 UTC
Labels: 1.11.2, bug, fixed in next release
