### ISSUE TITLE
Animania Mobs Not Affected By doMobSpawning Command

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#232] opened 2017-06-19 17:32 UTC
I have a world that I'm messing around with in creative and I didn't want mobs in it. If I'm right about how the /gamerule doMobSpawning command works, after I set it to false, mobs shouldn't spawn. I set it to false, and I went around and got rid of as many animals as I could find that were there before I did the command. I went back to my house and there were chickens and cows there. I'm 99% sure that they didn't walk there from somewhere else. I am using 1.10.2 and Animania version 1.1.5. I can try to give you more information if this isn't enough.

Edit: They are definitely spawning... Two bulls spawned under my porch (made of slabs so they didn't suffocate) and it's impossible to get under there. I would show you a picture but I don't know how to put one on here...

**Comment by capnkirok** [comment] 2017-06-19 17:50
Yeah, I had to do a few things to get 'families' to spawn together, so it probably doesn't follow normal MC spawning under that rule. But... I can certainly check for it. Didn't even think about that.

For images on github, you can just Copy/Paste. Pretty slick.

**Comment by capnkirok** [comment] 2017-06-19 17:52
Actually one more question... were all the mobs children or males?

**Comment by RaliaTheWolf** [comment] 2017-06-19 18:28
Oh cool! I'll keep that in mind for future use.

From what I saw, all of the animals except for cows and horses were male or children.

**Comment by capnkirok** [comment] 2017-06-19 18:33
Ok perfect. Yes, I know exactly where this occurs. Much appreciated.

**Comment by RaliaTheWolf** [comment] 2017-06-19 18:34
No problem! 

One more quick thing I forgot to mention: the pigs were male and female and children as well.

**Comment by capnkirok** [comment] 2017-06-19 21:43
Well, based on that last comment, it wasn't what I thought it was, so did a bit more research. 

/gamerule doMobSpawning false will disable all mob spawning, after world generation, for both passive and hostile mobs. However, animals will still generate in along with terrain as new chunks are created in the world. I do not think there is a way to prevent this in vanilla Minecraft.

However, if you want to turn off Animania spawning for sure, you can actually do this in the config, animal by animal. And of course you could just use the /kill command to kill everything.

I'm going to close this actually since it's working as intended and there's already a way to do this in the config.

**Closed by capnkirok** 2017-06-19 21:43 UTC
Labels: 1.10.2, 1.11.2
