### ISSUE TITLE
[1.12.2] Animania 1.3.4 can't handfeed cows with harvestcraft crops, rabbits won't breed and vanish on server restart

### ISSUE THREAD

**Issue by Gepett0** [capnkirok/animania#377] opened 2017-10-08 09:26 UTC
Hi,

didn't have cows before version 1.3.4 so I don't know if problem existed before,
but cows can't be handfed harvestcraft items; tried rye and barley so far.
Feeding harvestcraft items with the trough is possible.

After updating I lost all my sweet rabbits (around 10). I catched some new,
but the little guys won't breed no matter what I do. They are wealthy and eating like normal (trough+manual).
EDIT: After a server restart my 3 beloved rabbits vanished.

Hens + sheeps breed fine, still waiting for a calf though.
EDIT2: Although in the config their is a feeding timer i can feed a whole stack of any crop to any of my sheeps.

BR
Gepetto

**Comment by capnkirok** [comment] 2017-10-08 19:25
So you've listed several issues. It's easier if you separate these out in the future.

- Cows not eating Harvest Craft items is a bug. Thanks!
- Question: Are you using The One Probe or WAILA to see what's happening with your animals? Holding SNEAK while viewing your animals tells you exactly what's going on (Pregnant, Fertile, How long until birth etc.)
- Rabbits (on server) are breeding just fine. And they don't disappear. Try spawning some new rabbits from creative ( a male and a female into a pen and see what happens, if they breed or vanish). They have to be very close to each other to get pregnant.
- Cows are also breeding just fine. And the code is exactly the same as the other animals, so it wouldn't make sense.
- You can hand feed animals any time you want. They just won't go searching for food until they are hungry, this is not a bug.

**Comment by capnkirok** [comment] 2017-10-08 19:51
Also can't handfeed horses with Harvest Craft stuff

**Comment by capnkirok** [comment] 2017-10-08 20:04
Just confirmed Rabbits are disappearing... I know why. I will have to do a patch... again.

**Comment by Gepett0** [comment] 2017-10-09 15:53
Hi,

answering your points:

1. Null problemo ;-)
2. Using HWYLA 1.8.20-B35_1.12, WAWLA 1.12.2-2.5.245 and WailaHarvestability 1.12-1.1.12.
   Last time I checked yesterday it was a calf permanently showing 19:59 till next growth phase.
   Will check again today.
3. Will try this today too.
4. Will post test results in #378 to keep it simple.
5. That's okay. But feeding stacks of stacks in a single animal fells kind of fattening the poor guys
   or do you plan to introduce gooses? :-D

BR

**Comment by capnkirok** [comment] 2017-10-10 18:14
1. Ok this is fixed in 1.3.5 (coming soon)
2. Would recommend The One Probe, these are not supported (right now)
3. 'Breedable' is from HWYLA. But that is immaterial if you have a Buck and a Doe rabbit, they should breed. I tested this yesterday quickly and everything seemed fine. Have an idea.. .may have to do with our invisible friends.
4. thx
5. Yeah, maybe we add support for this, but later

**Closed** 2017-10-11 18:14 UTC
Labels: 1.10.2, 1.11.2, 1.12, bug, fixed in next release
