### ISSUE TITLE
suggestion/question animania 1.12.1 latest

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#334] opened 2017-09-19 05:14 UTC
would it be possible to turn down how many animals spawn? cause getting like 100+ spawns in a 7x7 chunk area is way to many so if possible pretty plz lower spawn rate?

**Comment by capnkirok** [comment] 2017-09-19 05:33
That does seem too high. You can manually turn them down in the config (reducing spawn probability etc). I will also check my defaults.

**Comment by CharCharthemonkey** [comment] 2017-09-19 05:37
plz do cause in my 1.12.1 world i literally have like 50 animals in 1 pond alone and some animals that spawn in deserts spawning in the plains biome

**Comment by CharCharthemonkey** [comment] 2017-09-19 05:38
also idk which way to set the number on the config to lower said spawns since its not exactly worded right lol

**Comment by capnkirok** [comment] 2017-09-19 05:42
Yeah, spawning is weird in MC. But it makes sense to those who have worked with it before.

Right now, most animals are between 8-16% of spawning in a particular chunk that has open space for an animal.

That's what Spawn Probability is. Would recommend you lower some animals to a number between 6-10 and create a new world and see what works.

**Comment by CharCharthemonkey** [comment] 2017-09-19 06:00
will do that ty also im guessing lower is less higher is more for spawn numbers

**Comment by capnkirok** [comment] 2017-09-19 14:35
Yes, that number is the percentage likelihood

**Comment by CharCharthemonkey** [comment] 2017-09-19 15:51
ok so gonna guess spawn probability is the one i need to lower to get less spawns but not sure so if its spawn limit then plz let me know?

**Comment by capnkirok** [comment] 2017-09-19 16:02
You can use both. Spawn probably means less likely to spawn, so fewer spawns. Spawn Limit limits the number of animals in 128 block that can spawn. Tune to your liking. You can practice on a test world.

**Comment by CharCharthemonkey** [comment] 2017-09-19 16:52
will do tho if i knew how id want them doing like previous versions where maybe 1-2 spawned per chunk but were more spread out if that makes sense

**Comment by capnkirok** [comment] 2017-09-19 23:49
Duplicate of #336

**Closed by capnkirok** 2017-09-19 23:49 UTC
Labels: confirmed, duplicate
