### ISSUE TITLE
Two little problems concerning animal spawning

### ISSUE THREAD

**Issue by Deing-Young** [capnkirok/animania#459] opened 2017-11-25 09:00 UTC
### Expected Behavior
1, If I set   B:"Spawn Animania Amphibians in world"=false   I could still spawn frogs and toads correctly via spawn eggs.
2, If I set   B:"Spawn Animania Amphibians in world"=true    and     I:"Spawn probability Frogs"=0      and
I:"Spawn probability Toads"=0    I could create worlds with no toads and frogs spawned naturally, but I could now spawn them via spawn eggs correctly.
The 2nd problem is some sort of continuation of the 1st one.

### Actual Behavior
1, The frogs and toads spawned are invisible, but I can hear them. Moreover, when I use the /execute command (/execute @e ~ ~ ~ say hi), I found out that they are called "unknown" instead of "frogs" or "toads" (and it also proves that they do exist).
2, CRASHED! Exception in server tick loop. Cannot create a new world (except The Void Flat world which does not spawn anything by default), everything stuck at "Creating new world", and I find a crash-report file.    The crash-report --> [http://paste.ubuntu.com/26040080/](url)   (Clicking this link seems not working, please try copy and paste.)

### Steps to Reproduce
As stated above. Just modify the config files and create a new world.
The following is exactly what I did:
First, you set the configs,
B:"Spawn Animania Rodents in world"=false
B:"Spawn Animania Amphibians in world"=true
I:"Spawn probability Frogs"=0
Then, you start minecraft, and first create a Flat world of the "Void" type, and check out the "unknown" ferrets of hamsters that you spawn with spawn eggs.
Next, you create a normal world, but this time, the game will crash. (If you did this previous to the Void world, you'll have to restart Minecraft).

### Version of Minecraft, version of Animania, Single Player or Server
1.10.2
animania-1.10.2-1.4.2    (some former versions on 1.10.2 also had this situation)
CraftStudioAPI-universal-0.3.0.87-mc1.10.2-beta
Single Player

### Screenshots encouraged
Uh.... Sorry, didn't get one, but I think I've described the situation quite explicitly.
And, I suppose these aren't big bugs, but I do hope you could fix them, if you have the time.

**Comment by capnkirok** [comment] 2017-11-27 18:27
Wow. You are right. The spawn prevention is not working as intended in 1.10, and may affect other versions. There are actually two issues, as you point out.

**Comment by capnkirok** [comment] 2017-11-27 18:38
Ok, this is fixed in development, and will be in next release (1.4.3). Same problem exists in 1.11 and 1.12.

**Closed** 2017-12-12 09:08 UTC
Labels: 1.10.2, 1.11.2, 1.12, bug, fixed in next release
