### ISSUE TITLE
Couple of Issues

### ISSUE THREAD

**Issue by xiinos** [capnkirok/animania#6] opened 2017-02-20 12:50 UTC
>>Troughs won't place if anything is on the blocks next too it. If there was a flower on a block next to a trough and you broke the trough on accident and then tried to replace it, it won't set down because the flower is next too where it would be placed.

>>Troughs full of wheat kept despawning.

>>When cows gave birth next too a fence, the baby would spawn on the other side of it.

>>Despite the breed of parents and complete separation from other animals, they would often have offspring of an unrelated breed. My first Angus pair had a Longhorn calf, a Hereford calf, and then the rest were Angus calves.

Just a few minor bugs that I noticed c:

**Comment by capnkirok** [comment] 2017-02-20 19:55
Thanks for the feedback! Haven't seen those first 3. But the last one I saw this morning! Kind of funny !

**Comment by capnkirok** [comment] 2017-03-01 21:33
- Trough placement has been changed
- Can't reproduce troughs of wheat despawning... are you still seeing the issue?
- Breeding should be fixed
- Will look into calves/fence thingy

**Comment by capnkirok** [comment] 2017-03-04 12:08
Hey @xiinos , are the troughs of wheat still de-spawning?

**Comment by capnkirok** [comment] 2017-03-05 17:52
I'm closing this. The calves fence thing is tagged in #45 
The troughs despawning is not reproducible
Others have been addressed.

**Closed by capnkirok** 2017-03-05 17:52 UTC
Labels: bug, fixed in dev
