### ISSUE TITLE
Seed still causing Compatibility issues :(

### ISSUE THREAD

**Issue by Erinbutt** [capnkirok/animania#68] opened 2017-03-21 01:29 UTC
_Sorry for being a noodge about it_
Using the latest 1.0.4 Version
Seeds still are causing problems with Forestry + Agricraft 
Shift+Right Click works for placing them, but still can't be use in the previously mentioned issue post, 
You can still place seeds by just right clicking as well.
Do configs need to be reloaded?

**Comment by WesCook** [comment] 2017-03-21 04:08
I regenerated configs and see the same issue.  Both RMB and Shift+RMB work for placing seeds.

**Comment by capnkirok** [comment] 2017-03-21 06:54
Yeah, really sorry guys. I did a crappy job of testing this one. Will do a stealth hotfix today

**Comment by WesCook** [comment] 2017-03-21 15:40
No worries, moo cow.  You're doing an excellent job on Animania so far!

**Comment by capnkirok** [comment] 2017-03-21 17:42
Hmm.... I see no problems with Forestry:
https://gyazo.com/4c196c928afa5609e7781e5e803155ba

**Comment by capnkirok** [comment] 2017-03-21 18:40
Ahhh ha ha ha! So, my code is fine. The problem is... the version that is up on Curse doesn't have this fix in it... yes... I forgot to rebuild after I made this last fix. Will update in a few hours...

😲

**Comment by capnkirok** [comment] 2017-03-21 19:37
Ok, I've added in code to ignore the two blocks you mention by default.. AND I've put in a config so you can make it use Shift-Right-Click to place.

**Comment by capnkirok** [comment] 2017-03-23 05:54
I'm closing this one

**Closed by capnkirok** 2017-03-23 05:54 UTC
Labels: compat, fixed in next release
