### ISSUE TITLE
Calf mobs hitbox is incredibly small and doesn't scale with its size.

### ISSUE THREAD

**Issue by Claycorp** [capnkirok/animania#220] opened 2017-06-12 19:11 UTC
The hitbox doesn't even cover the full baby mob.
As they grow the hitbox becomes a joke at how small it is.
See: http://i.imgur.com/7goi1zS.png

This makes it hard to do anything with them as they are so off misclicks are extremely common and "What is this" mods don't show anything unless you look at that tiny box.

**Comment by Tschipp** [comment] 2017-06-12 20:23
We are aware of this and will fix it.

**Comment by calloatti** [comment] 2017-06-19 13:38
Duplicate of https://github.com/capnkirok/animania/issues/118

**Comment by capnkirok** [comment] 2017-06-19 21:12
Closing because it's duplicate, but it is fixed in dev and will be next release :)

**Closed by capnkirok** 2017-06-19 21:12 UTC
Labels: duplicate
