### ISSUE TITLE
(MC: 1.11.2 Animania: 1.2.1) NPE / baby piglets / conflict with NetherEx

### ISSUE THREAD

**Issue by vektory79** [capnkirok/animania#275] opened 2017-07-14 14:05 UTC
Dedicated server is crashed when Minecraft generate new chunk with pigs.

NPE on entity tick update:

```
-- Entity being ticked --
Details:
        Entity Type: null (com.animania.common.entities.pigs.EntityPigletBase)
        Entity ID: 63121
        Entity Name: unknown
        Entity's Exact location: -1327,50, 66,00, 114,50
        Entity's Block location: World: (-1328,66,114), Chunk: (at 0,4,2 in -83,7; contains blocks -1328,0,112 to -1313,255,127), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
        Entity's Momentum: 0,00, 0,00, 0,00
        Entity's Passengers: []
        Entity's Vehicle: ~~ERROR~~ NullPointerException: null
```

[Full crash log](https://gist.github.com/vektory79/7ccfbaabdf2b68897b5a11655ce61bd7)

**Comment by capnkirok** [comment] 2017-07-16 16:15
Is there more to this, or maybe a client-side log as well? This only tells me that the server tried to generate a piglet, but it was null, which is strange.

It's possible this was a piglet that generates with a baby pigman riding it. Is there anything that would block a pigman from being spawned in your world? You may want to try setting the config option for AllowMobRiding to FALSE, and let me know if you still see the problem.

**Comment by Hootling** [comment] 2017-07-20 16:34
I think I am having the same crash as the original poster.
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  IvToolkit (IvToolkit-1.3.3.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 7/20/17 12:05 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at nex.handler.EventHandler.onLivingUpdate(EventHandler.java:407)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_EventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:531)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2005)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at nex.handler.EventHandler.onLivingUpdate(EventHandler.java:407)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_EventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:531)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2005)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: null (com.animania.common.entities.pigs.EntityPigletBase)
	Entity ID: 639
	Entity Name: unknown
	Entity's Exact location: -136.50, 64.00, -220.50
	Entity's Block location: World: (-137,64,-221), Chunk: (at 7,4,3 in -9,-14; contains blocks -144,0,-224 to -129,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Hootling'/170, l='New World', x=-170.35, y=79.24, z=-116.76]]
	Chunk stats: ServerChunkCache: 534 Drop: 0
	Level seed: -6615956970526181320
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (36,64,24), Chunk: (at 4,4,8 in 2,1; contains blocks 32,0,16 to 47,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1317 game time, 1317 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 57435 (now: false), thunder time: 154785 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 821692944 bytes (783 MB) / 2595749888 bytes (2475 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.1.2414 Optifine OptiFine_1.11.2_HD_U_B9 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2414.jar) 
	UCHIJAAAA	forge{13.20.1.2414} [Minecraft Forge] (forge-1.11.2-13.20.1.2414.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	craftstudioapi{0.3.0-beta} [CraftStudio API] (CraftStudioAPI-universal-0.3.0.86-mc1.11.2-beta.jar) 
	UCHIJAAAA	animania{1.2.1} [Animania] (animania-1.11.2-1.2.1.jar) 
	UCHIJAAAA	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJAAAA	nex{1.1.7.8} [NetherEx] (NetherEx-1.11.2-1.1.7.8.jar) 
	UCHIJAAAA	reccomplex{1.4.4-1.11} [Recurrent Complex] (RecurrentComplex-1.4.4-1.11.jar) 
	UCHIJAAAA	tconstruct{1.11.2-2.7.1.34} [Tinkers' Construct] (TConstruct-1.11.2-2.7.1.34.jar) 
	Loaded coremods (and transformers): 
IvToolkit (IvToolkit-1.3.3.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Hootling'/170, l='New World', x=-170.35, y=79.24, z=-116.76]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.11.2_HD_U_B9
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GTX 980M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`

**Comment by capnkirok** [comment] 2017-07-20 16:38
Yeah, I really don't know what is causing this yet, but at least it is limited to the EntityPiglet on 1.11.2, continuing to investigate and hope to have a hotfix this weekend.

**Comment by Hootling** [comment] 2017-07-20 16:43
Okey.  Will keep an eye out.  If you need more info/specific test i'm happy to help :)

**Comment by capnkirok** [comment] 2017-07-20 16:45
Did you happen to get a log on the client side?

**Comment by Hootling** [comment] 2017-07-20 16:48
the regular logs?  like latest.log and the .gz files?  I do have those. 

and dunno if this is helpful, at the spot the logs said the ticking entity was - there was prime pork on the ground in the exact coords.

**Comment by Hootling** [comment] 2017-07-20 17:42
I am fairly confident the problem is related to interaction with the mod NetherEx.  I just did about ten tests with just NetherEx and Animania, using the same world seed.

If NetherEx is turned off, no crash.  NetherEx is turned on, same crash in same spot every time.

seed: -6615956970526181320 
crash spot:  Entity's Exact location: -156.50, 70.00, -256.50

I was able to reproduce this crash several times.

**Comment by capnkirok** [comment] 2017-07-20 21:21
Ah! Thank you so much, I missed that. Yes, it's this line: nex.handler.EventHandler.onLivingUpdate(EventHandler.java:407)

I didn't catch the "nex" versus the vanilla "net" ... honestly why would you do that?

**Comment by capnkirok** [comment] 2017-07-20 21:25
Ok, this mod must do something with pigmen I am thinking.. because in Animania baby piglets very rarely spawn with a baby pigman riding them. I can put in some code to skip this if NetherEx is installed.

**Comment by Hootling** [comment] 2017-07-20 22:47
Yes, NetherEx does do something with pigmen.  It adds "Pigtificate" mobs and villages to the nether, a nether variant of Testificates.

If I disable the mob riding feature in Animania, that should probably handle it in the meantime I'd imagine.

Glad to help :)

*subliminal message:  DUCKS AND BARN OWLS*  -spooky noises-

**Comment by Hootling** [comment] 2017-07-20 23:13
I still get the crash with AllowMobRiding=false.

**Comment by Hootling** [comment] 2017-07-21 17:15
The fix pushed out by NetherEx does seem to have fixed the problem.  Flew around for about an hour doing other stuff this morning with no crashes.

Have a nice weekend thinking about ducks and barn owls.

Cheers.

**Comment by capnkirok** [comment] 2017-07-22 17:05
Gonna test it now before declaring victory :)

**Comment by capnkirok** [comment] 2017-07-22 17:39
Yep, all good. Closing. Fixed in this version of NetherEx: https://minecraft.curseforge.com/projects/netherex/files/2453861

**Closed by capnkirok** 2017-07-22 17:39 UTC
Labels: 1.11.2, compat, investigating
