### ISSUE TITLE
animal bug

### ISSUE THREAD

**Issue by CharCharthemonkey** [capnkirok/animania#578] opened 2018-02-21 18:23 UTC
### Expected Behavior
animals shouldnt be able to go through the mining world portal

### Actual Behavior
they go through the portal even know its the one u have to shift to use

### Steps to Reproduce
pick any animal and push him through it

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2                               1.4.6                        single player

### Screenshots encouraged
![2018-02-21_12 04 09](https://user-images.githubusercontent.com/30783285/36497763-da4551a0-1701-11e8-915e-5523ceb97984.png)

**Comment by Deshiba** [comment] 2018-02-21 18:27
Animals can go trough the nether portal just fine. I don't know if the mining dimension uses code to stop this from happening. Might be an issue with mining dimension

**Comment by CharCharthemonkey** [comment] 2018-02-21 18:29
the mining world portal forces u to sneak through to use according to the configs

**Comment by Deshiba** [comment] 2018-02-21 19:31
Can't find anything about it in the mining dimension documentation. Are you sure this doesn't happen with vanilla animals too?

**Comment by CharCharthemonkey** [comment] 2018-02-21 20:26
the only way it would even happen was if the animals shifted through the portal otherwise they would just walk through the one in the overworld and nothing would happen afaik

**Comment by Deshiba** [comment] 2018-02-21 20:39
I can't reproduce this with vanilla and mining dimension only, sheep just stand still inside the portal.
Can't reproduce this with vanilla, mining dimension and animania either. Tested with cows, pigs, chickens and horses

![2018-02-21_21 38 09](https://user-images.githubusercontent.com/10565800/36504102-af9511ea-174f-11e8-890c-a71ea118acfd.png)

**Comment by CharCharthemonkey** [comment] 2018-02-22 16:52
well weirdly ive seen this with animania animals able to pass thought the portal with ease and ik for a fact for players they have to sneak to use the portal

**Comment by capnkirok** [comment] 2018-02-22 18:04
Mmm... this needs to be controlled in Mining Dimension.

**Comment by Deshiba** [comment] 2018-02-22 19:06
I tried pushing trough several animals, it doesn't work with a fresh install of both mods.
-  Is this happening in a world where you upgraded the mods?
-  Are there more mods installed?
-  Have you tried resetting the mining dimension configs to default?
-  Have you mentioned this issue to the mining dimension dev?

**Comment by CharCharthemonkey** [comment] 2018-02-22 19:14
fresh world with other mods regenned the mining world configs and still happens and next on my list 
[Charlie's Immersive Pack 5-1.2.zip](https://github.com/capnkirok/animania/files/1749222/Charlie.s.Immersive.Pack.5-1.2.zip)

**Comment by capnkirok** [comment] 2018-02-24 12:00
Hey @CharCharthemonkey can you bring this up with the Mining Dimension dev? The animania animals are just entities like any other.

**Comment by CharCharthemonkey** [comment] 2018-02-24 21:15
will do thank you capnkirok

**Comment by Deshiba** [comment] 2018-02-24 21:52
Its not on github, look here:

https://bitbucket.org/Aroma1997/miningworld/issues

**Comment by capnkirok** [comment] 2018-03-16 20:43
Closing this one...

**Closed by capnkirok** 2018-03-16 20:43 UTC
