### ISSUE TITLE
Floating Eggs

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animania#205] opened 2017-06-07 17:50 UTC
I'm in MC version 1.10.2 and I have the latest version of Animania. My hens are laying their eggs in the nests, but they're also laying them vanilla chickens. I have vanilla animals turned off, so I know that there aren't any vanilla chickens around.

**Comment by Tschipp** [comment] 2017-06-07 17:58
duplicate of #201

**Closed by Tschipp** 2017-06-07 17:58 UTC

**Comment by capnkirok** [comment] 2017-06-07 18:22
Yeah, we're working on this one.
