### ISSUE TITLE
Hamsters causing client crashes after adding new mods

### ISSUE THREAD

**Issue by katubug** [capnkirok/animania#466] opened 2017-12-01 19:01 UTC
### Expected Behavior
Start up the game, log into server correctly.

### Actual Behavior
Client crashes upon login to server.

### Steps to Reproduce
Here is the crash report: [crash-2017-12-01_12.56.22-client.txt](https://github.com/capnkirok/animania/files/1522627/crash-2017-12-01_12.56.22-client.txt)

The mods we recently added are: InControl, Reliquary, Primitive Mobs, and Bailey's Dailies. What is frustrating is that I logged in to the server without issue after adding the mods earlier today. Now attempting to log in crashes the client. Server is fine. 

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.12.4-1.4.2
SMP but crash is client only.

### Screenshots encouraged
Nothing to screenshot.

**Comment by katubug** [comment] 2017-12-01 19:06
I'm not sure if this information is relevant, but here's the MultiMC console log of the crash:

[13:05:17] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Katu\Desktop\MultiMC\instances\Hardcore\minecraft\crash-reports\crash-2017-12-01_13.05.16-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
[0x7FED902AAA0] ANOMALY: meaningless REX prefix used
[0x7FED90148C0] ANOMALY: meaningless REX prefix used
[0x7FED90154B0] ANOMALY: meaningless REX prefix used
Process exited with code -1.
-------

Additionally, I removed InControl in case it was the issue, and it made no difference. I'll keep updating with the stuff I try.

**Comment by katubug** [comment] 2017-12-01 19:12
Removed PrimitiveMobs and I was able to log in properly. I'm guessing there's some sort of incompatibility there, but I can't imagine what.

**Comment by capnkirok** [comment] 2017-12-01 19:43
Hey Katabug!

Yeah, this is a tricky one. The problem is that I am using a particular way of storing data on an entity. This can cause issues when you add a mod that has entities to an existing world that has entities. The data points are stored in a stack. And new entities mess the stack up. Let me know what the PrimitiveMobs people say, if they have a solution.

It works fine if you were to start a new world of course...

PC

**Comment by capnkirok** [comment] 2017-12-01 21:17
Or worst case scenario.. you can remove the animania animals and spawn new ones, so the data references the correct location.

**Comment by katubug** [comment] 2017-12-04 19:10
Awesome, I was just about to come here and ask if I could do that. I will try that. Thank you!

**Comment by katubug** [comment] 2017-12-04 19:44
Eep, okay so. I removed Animania briefly, installed PrimitiveMobs, restarted the server. Then, I added Animania back in and restarted again.

Everything worked fine for about fifteen minutes, at which point I experienced a client crash.

This is the one that crashed me from the server:
[crash-2017-12-04_13.38.03-client.txt](https://github.com/capnkirok/animania/files/1528545/crash-2017-12-04_13.38.03-client.txt)

And here is the one that happened when I tried to log back in:
[crash-2017-12-04_13.41.11-client.txt](https://github.com/capnkirok/animania/files/1528546/crash-2017-12-04_13.41.11-client.txt)

**Comment by capnkirok** [comment] 2017-12-04 21:31
Yeah, I'm not sure it's going to work out. Bleh. I 'think' if you were to create a new world with both installed up front it should work fine... maybe you could test that?

I'm going to also research if there's another solution for the long term. This is the third time (in about a year) I've seen this come up.

PC

**Comment by katubug** [comment] 2017-12-04 21:38
I could try it, but it wouldn't help for this particular server, since no one wants to reset all our progress. I can test it in singleplayer though if you'd like the data?

**Comment by capnkirok** [comment] 2017-12-04 21:46
Yes, if you can let it run for a little bit in SP and see if it crashes. If so, then it could be a straight up conflict. I have a feeling that it will be fine though. Thank you!

**Comment by katubug** [comment] 2017-12-04 22:27
SP seems to be working fine. I created a new world, spawned in a bunch of PM Chameleons and Grove Sprites, and Animania Hamsters and Pygmy Goats. Sat afk in the field for a whole day and night cycle and had no issues.

**Comment by capnkirok** [comment] 2017-12-04 23:32
Thank you so much for testing! Yep, sounds like what I thought it was. For now, I think you'll have to survive with only one of the two animal mods. I'm going to do some more research.

**Comment by katubug** [comment] 2017-12-04 23:33
Ah well. Thank you for all your help! I really appreciate it.

**Comment by capnkirok** [comment] 2018-01-08 10:15
Ok, looks like this is a conflict with NBT data with the "Age" parameter for Tameable Entities. Found similar issue with Hedgehog and Ferret (see #496 and #495 )

**Comment by capnkirok** [comment] 2018-01-09 11:23
Ok, this one will be fixed in next release.

**Closed** 2018-01-22 02:21 UTC
Labels: 1.10.2, 1.11.2, 1.12, bug, fixed in next release
