### ISSUE TITLE
All non-vanilla liquids can be turned into vanilla milk

### ISSUE THREAD

**Issue by Partonetrain** [capnkirok/animania#442] opened 2017-11-19 21:52 UTC
### Expected Behavior

Nothing should happen if you put a bucket of a non-vanilla liquid into a crafting table.

### Actual Behavior

*Every* non-vanilla liquid bucket (i.e., any forge:bucketfilled) can be crafted into vanilla bucket of milk

### Steps to Reproduce

1. Have any mod with a liquid and Animania
2. Craft bucket of modded liquid into vanilla milk in any crafting table

### Version of Minecraft, version of Animania, Single Player or Server

1.12.2, Forge 14.23.0.2546, Animania 1.4.1, Singleplayer

### Screenshots encouraged

![2017-11-19_15 50 01](https://user-images.githubusercontent.com/19861808/32995923-56fbc194-cd41-11e7-86a3-d08bfa6a6bb3.png)

(that's Molten Iron from TConstruct, but I assure you it's worked with every forge:bucketfilled item)

**Comment by capnkirok** [comment] 2017-11-19 22:05
And I just built everything... lol. Hmmm..... OreDictionary doesn't seem to distinguish between different types of filled buckets... not good.

**Comment by capnkirok** [comment] 2017-11-19 22:18
Umm... I don't have this problem. Do you have minetweaker doing something to the recipes?

![image](https://user-images.githubusercontent.com/9628379/32996174-ce65908c-cd7f-11e7-9755-6115d8fe5d7d.png)

**Comment by capnkirok** [comment] 2017-11-19 22:19
Could be a Forge issue.... they messed around with Recipes very recently.

**Comment by Partonetrain** [comment] 2017-11-19 22:28
I do have CraftTweaker, but I know that doesn't add any recipes on its own. However, now that I think about it, it could be UniDict. Sorry for not realizing this earlier.

**Comment by capnkirok** [comment] 2017-11-19 22:30
Let me know if you find the issue.

**Comment by Nerezza** [comment] 2017-11-20 14:37
I imagine it's unidict. I had to remove that from one of my packs recently myself for having a few annoying issues.

**Comment by Tschipp** [comment] 2017-11-20 16:48
I remember fixing this exact issue on 1.11, and 1.12 uses the new jsons, so it shouldn't happen at all

**Comment by capnkirok** [comment] 2017-11-26 17:51
Ok, am closing this one. Have confirmed that it is working as intended. If you find the conflict/reason, please let me know!

**Closed by capnkirok** 2017-11-26 17:52 UTC
Labels: compat, question

**Comment by Partonetrain** [comment] 2017-11-26 22:05
Sorry, Thanksgiving festivities and such - I'm pretty confident it's UniDict, as all forge:bucketfilled items have the oredict entry listAllMilk. However, I'm not 100% sure. I'll let you know if it is solved for sure.

**Comment by WesTroy** [comment] 2017-12-13 19:13
Pretty sure this is Animania - tested today in 1.12.2:

1) Forge 14.23.1.2555 (Recommended) or .2564 (Latest)
- CraftStudio-1.0.0.93-mc1.12-alpha
- animania-1.12.2-1.4.3
- forestry_1.12.2-5.7.0.215 (for other buckets)
- jei_1.12.2-4.8.5.132
- jeiintegration_1.12.2-1.5.1.36 (for screenshots)

Screenshots: https://imgur.com/a/9MAIo
(Three examples: Animania Slop, Animania Holstein Milk, Forestry Ethanol)

Shows listAllmilk for all forge:bucketfilled items.
Probably a quick fix to ensure in-code that only the four milks are classified as such.

Hope this helps! Mod is amazing and always improving. Keep up the great work.
