### ISSUE TITLE
Chickens eat dropped seeds infinitely, stay hungry

### ISSUE THREAD

**Issue by Shurhaian** [capnkirok/animania#514] opened 2018-01-18 20:11 UTC
### Expected Behavior
When eating seeds that have been dropped on the ground (as entities), chickens should count as being fed. Ideally, they shouldn't eat extra seeds, as they don't when the seeds are placed on the ground.

### Actual Behavior
If seeds are thrown on the ground, the nearest chicken (at least leghorns) will devour them, but remain hungry and eventually starve, no matter how many seeds are thrown. Seeds eaten in this way will also not heal them, unlike seeds placed on the ground or fed directly by hand.

### Steps to Reproduce
Drop seeds in the world next to a hungry chicken.
Chicken will get heart particles and seeds will be consumed, but the chicken will remain hungry.

This is problematic when playing in a pack with Botania due to #429 making dispensers unable to properly place seeds on the ground, thus making chickens far higher-maintenance due to the inability to automate feeding them.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.4.3, singleplayer. Running the Enigmatica 2 modpack (pack v1.22)

### Screenshots encouraged
![2018-01-18_16 08 30](https://user-images.githubusercontent.com/5523258/35119073-35c28186-fc6a-11e7-91cc-e6a3129b7fd6.png)

**Comment by capnkirok** [comment] 2018-01-18 20:32
Will take a look. It definitely was working before, so I must have broken something.

**Comment by capnkirok** [comment] 2018-01-18 21:50
Umm... just re-read this... Animania chickens do not eat dropped items like seeds. Only if placed on ground or by hand. Some other mod in your pack is providing this functionality.  We are working on the known Botania issue.

**Comment by Shurhaian** [comment] 2018-01-18 22:11
Hmm. Must have misunderstood the project Curse page's section on chickens, then. I'll pass that on to the pack dev.

**Comment by capnkirok** [comment] 2018-01-20 16:17
FYI, in 1.4.4, chickens will be able to eat seeds and corn from troughs, which will also help

**Comment by ElvenChaos** [comment] 2018-01-22 02:47
Quark has an a feature that is toggle-able that allows animals to eat their animal-specific foods off of the ground (as in floating item entities, not tile entities like the seed TE that animania creates). On the [quark website](https://quark.vazkii.us/), the feature is found under the "automation" tab in the section labled "Hungry Animals." It is as follows:
`Hungry Animals that have a breeding food assigned to them will eat it from the floor at any time they can have it fed manually, provided the food is nearby. `

To disable this feature, you can either use the "website to config" functionality Vazkii provides, the "q" button in-game (on main menu on the left of the "mods" button), going to the quark mod options in-game (takes you to the same menu), or by manually editing the quark config (warning, long document). @Shurhaian you should try to disable the option, re-start your client if you need to, and play in SP with cheats on to test if the problem persists. Since animania animals now extend their vanilla counter-parts, this is probably the cause, as it wants to let "chickens" eat seeds, whereas animania wants different food interactions. This is just my guess though.

**Comment by Shurhaian** [comment] 2018-01-22 03:15
I found mention of that feature, yeah, and the option to turn it off. Doing so wouldn't address the underlying problem of feeding chickens - but them being able to eat from troughs definitely will.

I'd have raised the fact that Animania animals eat food on the ground (per Quark) but don't benefit from it as a bug on Quark's end, but Vazkii's bug-report standards want the newest version of Forge - and past experience has taught me not to mess with Forge versions if I don't have to, especially in a kitchen-sink pack; odds are too high that something will break.

**Comment by capnkirok** [comment] 2018-01-22 12:13
Hey guys, if this is indeed Quark, then there is really nothing I can do about it. Would recommend you turn the feature off and use troughs.

As for the dispenser issue, we continue to work on it. Hopefully we'll have it sorted soon (we have it work with Quark, just not Botania).

At any rate, closing this for now. Thanks for the details on the above.

**Closed by capnkirok** 2018-01-22 12:13 UTC
Labels: 1.10.2, 1.11.2, 1.12, compat
