### ISSUE TITLE
[1.11.2] Hamster taming crash

### ISSUE THREAD

**Issue by sdaddy** [capnkirok/animania#112] opened 2017-04-22 19:46 UTC
https://gist.github.com/sdaddy/e22ef798dcb19fd175c3d7d493088244

Found three hamsters chilling on a beach. I made friends with two of them, but the third one was totally unchill.

**Comment by Tschipp** [comment] 2017-04-22 19:58
Not able to reproduce. Can you please try and make a video of the bug?

**Comment by capnkirok** [comment] 2017-04-22 20:17
Thanks, ShawnDaddy. Ok, I was just about to publish the update and saw this. I'm going to put in an error check at the line where the crash occurred and see if that fixes it. I'll leave it open for now.

**Comment by capnkirok** [comment] 2017-04-22 20:31
Woot, fixed in dev :)

**Comment by sdaddy** [comment] 2017-04-22 20:39
I figured since I took the time to record it and turn into gif, I'll post the link. :-P
http://i.imgur.com/MXxdeA9.gifv

**Comment by Tschipp** [comment] 2017-04-22 20:43
Thanks for the gif! ~~Weird how this happened without having an empty inventory... did you only have items in your hotbar or also in your main inventory?~~
Apparently when you use the last hamster food item the game crashes, no matter if your inventory is empty or not. Anyway, fixed in dev :)

**Comment by capnkirok** [comment] 2017-04-22 20:44
That third hamster still needs a friend :)

**Closed** 2017-04-22 21:18 UTC
Labels: 1.11.2, bug, fixed in next release
