### ISSUE TITLE
These bulls hold a grudge longer than my ex girlfriends.

### ISSUE THREAD

**Issue by calloatti** [capnkirok/animania#114] opened 2017-04-23 12:54 UTC
I mean, guys, I just wanted to kill that creeper, sorry I hit you. Can we let it go already? What do I have to do to make it stop?

Also, all of you team up on me? I just hit you, not any of your pals over there.

animania-1.10.2-1.0.4.7
Minecraft 1.10.2

**Comment by Tschipp** [comment] 2017-04-23 17:11
Life is tough, so are bulls. Disabling the 'modesty flag' in the config will make them less agressive. (not really tho :P)

**Comment by capnkirok** [comment] 2017-04-23 18:45
Ha ha ha. Yeah, don't hit the bulls. 

If you sprint away from them, and get out of their range, they will ignore you... or you can logout and log back in.

But... I don't think I'll change this....

**Comment by capnkirok** [comment] 2017-04-23 18:45
Or you can use a Cloud Pet and turn them into steaks. I do all my testing with Inventory Pets installed 💯

**Comment by capnkirok** [comment] 2017-04-23 18:46
But... Teaming up... yeah.. that needs to be fixed. That is not the way bulls work.

**Comment by Tschipp** [comment] 2017-04-23 19:01
@capnkirok I always thought that was intended... Either way I think it fits, I was about to suggest that the bulls also become angry when you hit a cow or a calf. Call it a feature, not a bug! :D

**Comment by capnkirok** [comment] 2017-04-23 20:25
Yeah.... not a bug. Let's leave it here and put that protective thing in.

**Comment by Jomik** [comment] 2017-06-07 13:40
The range on the bulls are crazy though. I get hit through fences, when I'm at least 2 blocks away from the fence. (Counting the half block of the fence.)

**Comment by capnkirok** [comment] 2017-06-08 21:00
Yeah, and they are armor piercing. Because, you know, horns.

**Comment by capnkirok** [comment] 2017-06-10 11:50
Ok, if you get far enough away they will reset their aggro. Will be in next release.

**Comment by capnkirok** [comment] 2017-06-10 12:15
Oh and left the group attack on.

**Comment by Jomik** [comment] 2017-06-10 12:50
@capnkirok For pigs too?

**Closed** 2017-06-11 23:35 UTC
Labels: 1.10.2, 1.11.2, added in next release, enhancement, priority: low
