### ISSUE TITLE
Peafowl eggs

### ISSUE THREAD

**Issue by CrazyBeanie** [capnkirok/animania#264] opened 2017-07-09 20:15 UTC
Do the peafowl eggs take longer to hatch than the chicken eggs or is this a possible glitch?  I have been waiting 5 total Minecraft days for the peachicks to hatch and nothing has happened.  I have also tried to keep the males near the nest but no luck.

**Comment by montxen** [comment] 2017-07-09 20:22
Ok, when I got version 1.2.1? I think is the newest update the peafowl eggs hatches, so sorry to bother

**Comment by capnkirok** [comment] 2017-07-10 00:57
I didn't get to this one, but my suspicion is that your males are not nearby. Would recommend a lead or a fence to keep them nearby. Also you can try reducing or changing hatching times in config.

I have other complaints saying they hatch too quickly.... 

Out if curiosity, what are the breeds of the female and male?

**Comment by CrazyBeanie** [comment] 2017-07-10 01:51
Thank you for the tip and are you talking about the peafowl breeds for the fall damage?  If so it is both breeds, indian blue and white.

**Comment by capnkirok** [comment] 2017-07-23 19:27
Fall damage is under another bug #265 
And hatching is working as intended, can only think that your male peacocks are not near enough to the nest.

Closing this one. Let me know if you are still having issues :)

**Closed by capnkirok** 2017-07-23 19:27 UTC
